### PR TITLE
fix: floatinginput type changes

### LINKED ISSUE #435: FloatingLabelInput    type={inputType} not switching
### Describe the bug

Something is wrong with FloatingLabelInput   

I´m trying to show/hide Passwords on:click. so type= will change form "password" to "text"

If I use the same logic for color= then its working.

VSC is also complaining that (property) type?: InputType | undefined

```
<script lang="ts">
	import { FloatingLabelInput,  Button } from "flowbite-svelte";
	
	let show_password = false;
	
        let InputType = "password";
       	let inputColor = "red";
	
	$: inputColor = show_password ? "red" : "green";
	$: inputType = show_password ? "text" : "password";
</script>

<FloatingLabelInput
                id="floating_password"
                label="Password"
                color={inputColor}
                **type={inputType}**
                class="mb-4"
                autocomplete="current-password"
/> 

```

### Reproduction

?

### Flowbite version and System Info

```shell
latest
```

### PR DESCRIPTION
**Pull request by jjagielka**
Closes #435 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by Rar9** [comment]
I updated to 0.28, but issue remains

**Comment by Rar9** [comment]
<script>
import { FloatingLabelInput, Helper, Button } from "flowbite-svelte";
import Icon from "@iconify/svelte";
	
	let show_password = false;

	$: inputColor = show_password ? "red" : "base";
	$: inputShow = show_password ? "text" : "password";
	
</script>		

		<div class="w-full relative">
			<FloatingLabelInput
				id="floating_password"
				label="Password"
				color={inputColor}
				type={inputShow}
				autocomplete="current-password"
				class="mb-4"
			/>

			
			<div
				on:click={() => (show_password = !show_password)}
				class="absolute top-1/2 transform -translate-y-1/2 right-2 z-10"
			>
				<Icon
					icon="bi:eye-slash-fill"
					color="base"
					width="32"
					height="32"
					class={!show_password ? "hidden" : "h-5 w-5"}
				/>

				<Icon
					icon="bi:eye-fill"
					color="gray"
					width="32"
					height="32"
					class={show_password ? "hidden" : "h-5 w-5"}
				/>
			</div>
		</div>

**Comment by jjagielka** [comment]
Your example works form perfectly.
image

image

**Comment by Rar9** [comment]
Great, so where is the bug? 

The toggle only seams to work if I add Key but this will clear the input 

{#key inputShow}
....
{/key}

For the time being I´ll try your TOGGLE Code as it looked cleaner...

**Comment by Rar9** [comment]
Ok if I use your type of defining an input it works

```
let show_password = false;
type={show_password ? "text" : "password"}

<FloatingLabelInput
			id="floating_password"
			label="Password"
			**type={show_password ? "text" : "password"}**
		/>
```
		
**But not if its using  a variable of type InputType** 

```
$: inputType = show_password ? "text" : "password";

<FloatingLabelInput
			id="floating_password"
			label="Password"
			**type={InputType}**
		/>

```

**Comment by Rar9** [comment]
OK i found the issue Thnaks

**Comment by jjagielka** [comment]
What was the issue? For the records only.

**Comment by Rar9** [comment]
a stupid Input vs input

**Comment by Rar9** [comment]
I its possible to add <InputAddon> to FloatingLables??

So i can add easily a pre/suffix  or icons before /after to the input field?

**Pull request merged**
