### PR TITLE
Added touchevent forwarding to Buttons

### PR DESCRIPTION
**Pull request by Daschi1**
## 📑 Description

I noticed that the Button components do not forward the touchevents. However, these are essential for mobile development. So I added them to the list of forwarded events.

## Status

- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
> I noticed that the click event wasn't working there, possibly due to WebKit behavior. 

Can you tell me which one was not working?

**Comment by shinokada** [comment]
Thank you for your PR.
Can you check other components that have the `on:click` event forwarding?
If you find more, please create other PRs.

**Comment by Daschi1** [comment]
Yes, there are several other components where this issue is present. Would it be more appropriate to create individual pull requests for each one, or would one comprehensive pull request encompassing all of them be preferable?

Please note that my schedule is quite busy at the moment, but I will strive to implement these changes as soon as I find some free time.

**Comment by shinokada** [comment]
@Daschi1 Thank you for your contribution. I think one by one or a couple of components rather than one PR of all since API is changing quite often.

**Pull request merged**
