### PR TITLE
fix: typescript declarations for import.meta.glob

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
Typescript declaration for the import of markdown files in `index.ts` file.

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
What are you trying to solve with this PR?

**Comment by jjagielka** [comment]
`npm run check`

**Comment by shinokada** [comment]
There are 32 errors. Which one, may I ask?

**Comment by jjagielka** [comment]
All of those:
```text
Error: Property 'metadata' does not exist on type 'unknown'. 
    iterableExampleFiles.map(async ([path, resolver]) => {
      const { metadata } = await resolver();
      return {
```

**Pull request merged**
