### PR TITLE
Update Navbar.svelte

### PR DESCRIPTION
**Pull request by MSufianS**
Issue with container

Closes #

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
What do you want to achieve by this?
Can you explain it?

**Comment by MSufianS** [comment]
> What do you want to achieve by this? Can you explain it?

Because the Navbar always include a container.

**Comment by wrabit** [comment]
@MSufianS it already has api, see #561

**Comment by xmlking** [comment]
i am also got impacted with this change

**Comment by shinokada** [comment]
I close the PR for now.
Thank you for your contribution.
I'm looking forward to see future PRs.

**Pull request closed without merging**
