### PR TITLE
fix: color flicker when changing theme using DarkMode

### PR DESCRIPTION
**Pull request by 524c**
## Using the DarkMode component I noticed that the theme colors were always flashing. The reason is the colors load before the onMount function sets the theme color.

See these videos, please:

### Before this patch:
https://user-images.githubusercontent.com/527641/193426844-53ca6292-998d-4304-8b59-48ee42140f78.mp4

### And after the patch:
https://user-images.githubusercontent.com/527641/193426955-4c22c110-a0b5-4d82-b015-5ae8dcf7df9e.mp4

## ✅ Checks

- ✅ All the tests have passed
- ✅  My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
Thank you for the PR.
I'm wondering if this works for Svelte as well.
Is it possible to test it on Svelte?

```
npm create vite@latest myapp -- --template svelte
cd myapp
npm install
```

And install flowbite-svetle etc.

**Comment by 524c** [comment]
> Thank you for the PR. I'm wondering if this works for Svelte as well. Is it possible to test it on Svelte?
> 
> ```
> npm create vite@latest myapp -- --template svelte
> cd myapp
> npm install
> ```
> 
> And install flowbite-svetle etc.

> 
Hi, I'm currently using your template for some testing and it works perfectly with it:
https://github.com/shinokada/flowbite-svelte-starter

**Comment by shinokada** [comment]
Yes, it is using SvelteKit.
It works fine with SvelteKit.
But some users are using Svelte not SvelteKit.
So we need to test it with Svelte.
Can you try it?

**Comment by 524c** [comment]
> Yes, it is using SvelteKit. It works fine with SvelteKit. But some users are using Svelte not SvelteKit. So we need to test it with Svelte. Can you try it?

ok, i will test and let you know.

**Comment by jjagielka** [comment]
@524c - thanks for that PR. Seems like a increase performance (no flicker) is evident.

Question though. Why have you made other not necessary changes:
- removed typescript annotations
- changed svelte `{#if} .. {/if}` directive to general `hidden` class usage?

**Comment by 524c** [comment]
> @524c - thanks for that PR. Seems like a increase performance (no flicker) is evident.
> 
> Question though. Why have you made other not necessary changes:
> 
> * removed typescript annotations
> * changed svelte `{#if} .. {/if}` directive to general `hidden` class usage?

Hello, @jjagielka, about these two points:
The removal of the typescript annotation was unintentional, but since the value is static, the typescript already infers the type. Anyway, I can make a new commit with the type.

And about the {#if} ..{/if} directives, it was because the SVG icons weren't rendered as expected. It's easier to understand by watching this video below:

https://user-images.githubusercontent.com/527641/193464515-c0338408-39d8-48b9-ae8e-46b325608316.mp4

**Comment by jjagielka** [comment]
I can't reproduce that bug. What browser/os do you use for that?

Another point. You have as well removed the extra line:
`dark = window.document.documentElement.classList.contains('dark');`
that should be in `if(window) { }` section. This line makes sure the initial stat of the icon is correct.

**Comment by 524c** [comment]
> I can't reproduce that bug. What browser/os do you use for that?
> 
> Another point. You have as well removed the extra line: `dark = window.document.documentElement.classList.contains('dark');` that should be in `if(window) { }` section. This line makes sure the initial stat of the icon is correct.

You're right, this line shouldn't be removed.
About the bug:
In the video it was on a MacOS v13/Chrome v106.
On MacOs, this bug also occurs on Firefox v105 and Safari v16.

On another station I tested it on Windows 10, Chrome v105 and the bug also occurs.

**Comment by jjagielka** [comment]
Wait. So what's the bug?
- the overlap of two icons one over the other - as on the video above 
- or the icon moon when dark is set after the refresh?

**Comment by 524c** [comment]
> Wait. So what's the bug?
> 
> * the overlap of two icons one over the other - as on the video above
> * or the icon moon when dark is set after the refresh?

Both things happen when I'm using the {#if}..{/if} directive.

**Comment by jjagielka** [comment]
The second case is caused by the lack of initial setting of the `dark` variable - see the extra line removed.

The overlapping icons is something I have never seen (using different browser on windows and linux). I have not tested it on macOS, but I can't see how that can happen.

@shinokada - you're the macOS user, have you ever seen the overlapping dark mode icons (moon and sun at the same time)?

**Comment by 524c** [comment]
> dark = window.document.documentElement.classList.contains('dark');

I remembered why I removed that line.

The 'dark' variable was only used in the {#if}..{/if} directive. With the change I made it is not necessary anymore, since the initial mode is read inside <svelte:head> </svelte:head>

**Comment by jjagielka** [comment]
In fact putting that line `dark = window.document.documentElement.classList.contains('dark');` does not solves the issue as `<svelte:head />` is run before the component is created so the setting the `dark` variable has no impact.

I must admit that your purely css solution solves the problem of initialization. 

I'm OK to approve that PR.

**Comment by 524c** [comment]
> In fact putting that line `dark = window.document.documentElement.classList.contains('dark');` does not solves the issue as `<svelte:head />` is run before the component is created so setting the `dark` variable has no impact.
> 
> I must admit that your purely css solution solves the problem of initialization.
> 
> I'm OK to approve that PR.

Hi, although it passes all tests, @shinokada informed me that some users use flowbite with esvelte directly, not just with esveltekit.  I'm building a simple project using just esvelte to validate this and soon I'll share the repository with you to evaluate, ok?

**Comment by 524c** [comment]
> Yes, it is using SvelteKit. It works fine with SvelteKit. But some users are using Svelte not SvelteKit. So we need to test it with Svelte. Can you try it?

Hi, I used a Svelte + Tailwind project as a base and made adaptations to include Flowbite + this PR and everything seems to work OK too.
If you want to check it out, it's this repo => https://github.com/524c/Svelte-Tailwind

**Comment by 524c** [comment]
> Thank you for the PR. I'm wondering if this works for Svelte as well. Is it possible to test it on Svelte?
> 
> ```
> npm create vite@latest myapp -- --template svelte
> cd myapp
> npm install
> ```
> 
> And install flowbite-svetle etc.

Hi, I used a Svelte + Tailwind project as a base, made adaptations to include Flowbite + this PR and everything seems to work OK too.
If you want to check it out, it's this repo => https://github.com/524c/Svelte-Tailwind

**Comment by jjagielka** [comment]
I can confirm the patch works.

As for the initial small flicker:
- I can only observe it with `npm run dev`, but I can't notice it with `npm run build; npm run preview`
- you have put `tailwind.css` initialization in `Stylesheet.svelte` i.e. as component so that can delay the loading. Why don't you use the more standard solution with local `tailwind.css` file?

**Comment by 524c** [comment]
> I can confirm the patch works.
> 
> As for the initial small flicker:
> 
> * I can only observe it with `npm run dev`, but I can't notice it with `npm run build; npm run preview`
> * you have put `tailwind.css` initialization in `Stylesheet.svelte` i.e. as component so that can delay the loading. Why don't you use the more standard solution with local `tailwind.css` file?

Yes it is easier to notice this delay in dev mode. I had already loaded tailwind in a conventional way, but it made no difference in my tests, I even made a commit just now with this change. But back to PR, everything seems OK in both cases, with Svelte and Sveltekit. Congratulations on Flowbite. Of all the ones I studied to use in my project with Sveltekit, this was the one I liked the most. I'll keep an eye out and if I find any new opportunities to contribute I'll do it.

**Comment by jjagielka** [comment]
@shinokada we can merge that patch. Even if that short flicker is there, it's better than the current solution.

**Pull request merged**
