### PR TITLE
Tooltips update

### PR DESCRIPTION
**Pull request by shinokada**
Update the custom style CSS.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by jjagielka** [comment]
Your recent change is against the `Frame` standard. Custom color on `Frame` is achieved by setting the `color` to `none` and providing the appropriate classes in `class`. 
You've introduce the `customColor`:
```svelte
<Tooltip
  triggeredBy="#custom"
  placement="right"
  style="custom"
  tipClass=""
  class="p-4 text-lg font-medium"
  customColor='bg-purple-500 text-gray-100'
  arrow={false}
>
```
while it should be more like:
```svelte
<Tooltip
  triggeredBy="#custom"
  placement="right"
  style="custom"
  tipClass=""
  class="p-4 text-lg font-medium bg-purple-500 text-gray-100"
  color='none'
  arrow={false}
>
```
The reason I'm against `customColor` as set of classes is that it's correct syntax to do something like
```svelte
<Tooltip
  class=""
  customColor="p-4 text-lg font-medium bg-purple-500 text-gray-100"
>
```
with the same effect as above.

**Comment by shinokada** [comment]
The original code was giving an error about `colors[style]`. You set the default as `color="custom"` and there is no `custom` in `const colors`.

**Comment by jjagielka** [comment]
Fair point. So we should add `custom` to `const colors` and map it to `none`. Then we can avoid the line `color={style === 'custom' ? color : 'none'}`

**Comment by shinokada** [comment]
May be `undefined` may be better than `none`.
Using `none` may result with CSS `class="none ...`.

**Comment by jjagielka** [comment]
'color' is passed down to 'Frame' and there it falls into 'bgColor[color]' resolving to 'undefined'. So no danger of CSS 'class=none'.

**Comment by shinokada** [comment]
Got it.
You don't mind creating a PR when you have time?

**Comment by shinokada** [comment]
Arrow outline is missing.
image

**Comment by jjagielka** [comment]
This is how it looks at Flowbite.com

image

**Comment by shinokada** [comment]
An issue is created at flowbite.com
https://github.com/themesberg/flowbite/issues/296

**Pull request merged**
