### PR TITLE
fix: darkmode flicker

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description

Addresses #782 

This should cause no flicker, but I have removed the `initialTheme`.

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
Is there any way we can add initialTheme? 
Some users want to have the dark mode as their theme.

**Comment by jjagielka** [comment]
The easiest is to set their `app.html` to:
```html
<html class="dark" lang="en">
```

**Comment by Maxiviper117** [comment]
> The easiest is to set their `app.html` to:
> 
> ```
> <html class="dark" lang="en">
> ```

Simply enough change, would be helpful for others to mention this in the documentation that if they want the initial theme to be Dark then they need to make this small change, whilst still allowing website users to switch back to light theme.

**Comment by shinokada** [comment]
@jjagielka Using `<html class="dark" lang="en">` won't work anymore.

**Comment by jjagielka** [comment]
I've check on my side:
- works for Firefox
- doesn't work for Chrome

Can you please confirm?

**Comment by shinokada** [comment]
Confirmed. Edge, Safari don't work either.

**Pull request merged**
