### PR TITLE
feat: add voice search component

### PR DESCRIPTION
**Pull request by oune**
Closes # 

## 📑 Description

add voice search component and doc

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest version

## ℹ Additional Information

If your branch is behind the upstream master, I will have difficulties to merge the request. Please fetch the latest version of the branch:

```sh
git checkout your-branch
git pull upstream master
```

or

```sh
git checkout your-branch
git pull --rebase upstream master
```

### CODE REVIEW

**Comment by shinokada** [comment]
Thanks for your PR. It has been merged.

**Comment by shinokada** [comment]
@oune Please join the [Discord Flowbite channel](https://discord.com/channels/902911619032576090), if you are interested.

- We have [Flowbite-Svelte](https://discord.com/channels/902911619032576090/928736443218665563) channel. 
- I will request to invite you to an internal svelte-library channel. 

Let me know your Discord user name.

**Comment by oune** [comment]
My discord name is oune#6436 thank you

**Comment by shinokada** [comment]
Thanks. Did you join to [the Flowbite channel](https://discord.com/channels/902911619032576090)?

**Comment by oune** [comment]
I tried join the channel few minuets ago but i had error message

**Comment by shinokada** [comment]
Can you try this one?
[Join the Flowbite Discord Server](https://discord.gg/4eeurUVvTy)

**Comment by oune** [comment]
sucess! thank you

**Pull request merged**
