### PR TITLE
docs: fix breadcrumb import from

### PR DESCRIPTION
**Pull request by frailbongat**
## 📑 Description

Fix breadcrumb import from

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest version

## ℹ Additional Information

From

```svelte
  import { Breadcrumb } from '$lib/index'
```

To

```svelte
  import { Breadcrumb } from 'flowbite-svelte'
```

### CODE REVIEW

**Comment by shinokada** [comment]
Thanks for the catch.
I will merge it soon.

**Comment by frailbongat** [comment]
> Thanks for the catch. I will merge it soon.

No problem, glad I can help. Cheers 🍻

**Comment by shinokada** [comment]
Since I merged your last PR, my main is one commit ahead than this PR.
Could you pull `upstream`.
Can you try this and let me know.

```
git checkout your-branch
git pull upstream main
```

**Comment by frailbongat** [comment]
@shinokada Successfully merge to latest main

**Pull request merged**
