### PR TITLE
Improving docs

### PR DESCRIPTION
**Pull request by chinmaykh**
Reordered doc for clarity & applied md rules for the same.

## 📑 Description

Improved `docs -> compiler speed -> requirements`. Felt putting the typescript point after the point on editor warning would enhance clarity. The former version would loose non TS audience who assume the section is pertinent only to TS devs. I've also added some md styling along the md guidelines for documentation. I have run the test script and I do not observe any difference in results from tests.

## Status

- [x] Not Completed
- [ ] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by chinmaykh** [comment]
I do not know how to check the page using validator, and have thus left it open to the community. That is the only remaining check.

**Comment by chinmaykh** [comment]
@shinokada I've made this PR as per your direction. What do you think?

**Comment by chinmaykh** [comment]
@shinokada can you merge this now?

**Comment by chinmaykh** [comment]
@shinokada will you merge this now?

**Comment by shinokada** [comment]
I can't see any difference or improvement.
And also `.svelte-kit/tsconfig.json` is not correct.

**Comment by shinokada** [comment]
Thank you for taking the time to submit this PR. 
Even though we weren’t able to merge it, we appreciate your effort and contribution to the project.
We are looking forward to your continued contributions and collaboration on this project.

**Pull request closed without merging**
