### PR TITLE
Enable lint in worflow and format all files

### PR DESCRIPTION
**Pull request by koplas**
## 📑 Description

Formats all files and enables linting in the GitHub Action workflow. This simplifies contributions that don't result in many line changes.

## Status

- [x] Not Completed
- [ ] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
A question: How did you make multi-line to single line? Is it a VSCode plugin or prettier command?

image

**Comment by koplas** [comment]
> A question: How did you make multi-line to single line? Is it a VSCode plugin or prettier command?
> 
> image

By running `pnpm prettier --write .` it should format all files. You can also install the prettier as a VS Code plugin: https://www.freecodecamp.org/news/how-to-use-prettier-in-visual-studio-code/.

**Comment by koplas** [comment]
ESLint reports 163 errors. Some fixes may result in breaking changes. I will set this pull request to draft for now.

**Comment by koplas** [comment]
There are a couple more issues when running `pnpm check`. I will set this pull request to draft again.

**Comment by koplas** [comment]
Fixing all errors at once was to complicated. I created a pull request that only addresses the formatting issue: https://github.com/themesberg/flowbite-svelte/pull/1445.

**Pull request closed without merging**
