### PR TITLE
fix: accordion slots + docs

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
Quick fixes to `Accordion`:
- common `AccordionCtxType`
- `slot name=body` changed to default slot
- update in doc and examples

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
Can you check the icon position?

image

**Comment by shinokada** [comment]
And search input?
It has "ch" after the button.

image

**Comment by jjagielka** [comment]
Sure. It was working when I finished. Need to find out what went wrong.

**Comment by jjagielka** [comment]
Found the problem. I'll correct it when back at home. 2-3 hours.

**Pull request merged**
