### PR TITLE
fix: Refine the typing of the ListGroup's slot

### LINKED ISSUE #1272: Listgroup Example has a type error
### Describe the bug

The example for [Listgroup with links](https://flowbite-svelte.com/docs/components/list-group#List_group_with_links) results in a typing error in VSCode, but the application runs fine.

The `{item.name}` shows an error for `name`:

> Property 'name' does not exist on type 'string'

### Reproduction

<script>
  import { Listgroup } from 'flowbite-svelte';
  let links = [
    { name: 'Accordions', href: '/docs/components/accordion', current: true },
    { name: 'Alerts', href: '/docs/components/alert' },
    { name: 'Badges', href: '/docs/components/badge' },
    { name: 'Breadcrumbs', href: '/docs/components/breadcrumb', attrs: {target: '_blank'} }
  ];
</script>

<Listgroup active items={links} let:item class="w-48">
  {item.name}
</Listgroup>

### Flowbite version and System Info

```shell
latest
```

### PR DESCRIPTION
**Pull request by fdevillard**
Closes #1272

## 📑 Description

Refine the typing of the `ListGroup` such that the following code type checks correctly:
```
<script lang="ts">
let myItems = [
    {name: "test1", id: 1},
    {name: "test2", id: 2},
]
</script>

<Listgroup items={myItems} let:item>
    {item.name}
</Listgroup>
```

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

## Summary by CodeRabbit

- **New Features**
	- Enhanced flexibility of the List Group component by allowing it to accept a broader range of item types.
	- Improved type safety and reusability for better integration in various contexts.
- **Documentation**
	- Updated the component's documentation to reflect the new generic type functionality.

### CODE REVIEW

**Comment by shinokada** [comment]
Will the following work without adding type definition to the script tag?

```
// $lib/types.ts
import type { ComponentProps } from 'svelte';
import type { ListGroupItemType } from '../types';
import type Frame from '../utils/Frame.svelte';

export type T = ListGroupItemType | string;

export interface ListGroupProps extends ComponentProps<Frame> {
  items?: T[];
  active?: boolean;
}

export interface ListGroupSlots {
  default: { item: T; index: number };
}
```

```
//src/lib/list-group/Listgroup.svelte
<script lang="ts">
  import type { ListGroupProps, ListGroupSlots, T } from './ListGroup';
  import { createEventDispatcher, setContext } from 'svelte';
  import { twMerge } from 'tailwind-merge';
  import Frame from '../utils/Frame.svelte';
  import ListgroupItem from './ListgroupItem.svelte';

  type $$Props = ListGroupProps;
  type $$Slots = ListGroupSlots;

  const dispatch = createEventDispatcher();
  export let items: T[] = [];
  // more lines
</script>
```

**Review by ziadalzarka — APPROVED** [review]

**Comment by fdevillard** [comment]
> Will the following work without adding type definition to the script tag?

It could also, but the behavior would be slightly different. My understanding of the component (which is shallow, as I haven't used it a lot) is that:
- you can give list of strings to the `ListGroup` and then the slot's  `item` is  a `string`,
- or, you can give a list of `ListGroupItemType` and the slot's `item` is a `ListGroupItemType`.

If I understand your proposal correctly, we would loose this information. The typing would support a `ListGroupItemType` with a slot receiving a `string`. However, the actual value would be a string.

That's what the `generics` is expected to solve.

**Comment by shinokada** [comment]
I have no problem using the `generics`. It isn't common to use type in the `script` tag.

**Comment by shinokada** [comment]
Thank you for the PR.

**Comment by fdevillard** [comment]
Oh thank you for the merge :+1: Sorry for the delay, I didn't see the notification 🙈

**Pull request merged**
