### PR TITLE
Speed

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
`Speed Dial` component. All functionality implemented, although doc page more condensed.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by jjagielka** [comment]
I've noticed that as well. I've just copied `aria-controls` from Flowbite.com. Would be worth checking with them.

I think we can remove it for now and add it back when the issue is cleared out.

**Comment by jjagielka** [comment]
ad 1. What do you mean by ’remove all the slot attributes’?

**Comment by shinokada** [comment]
Since svg doesn't have[ `slot` attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute#s), we should remove `slot="icon"`.

**Comment by shinokada** [comment]
Well it is Svelte slot, so I'm not sure. We just ignore?

**Comment by jjagielka** [comment]
`slot="name"` is used to replace the default `+` sign inside the blue button to some other `svg`: see the "dropdown menu" or "alternative menu" examples where "+" is replaced by "pen" or three dots "...".

**Pull request merged**
