### PR TITLE
fix: Update tailwind background opacity classes to tw3

### PR DESCRIPTION
**Pull request by jordigagomerino**
Closes #

## 📑 Description
Some components like Button, Drawer, Modal and the backdrop util are using Tailwind 2 classes for manage background opacity (Ex. The drawer uses bg-opacity-75). 
Now in Tailwind 3 there is a opacity modifier (Ex. The drawer will use bg-gray-900/75) 
See [Tailwind 3+ Background Opacity](https://tailwindcss.com/docs/background-color)

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information

I removed the prop bgOpacity from the drawer as is not needed anymore I don't know if that count as a breaking change or not. If I have to update something please let me know.

### CODE REVIEW

**Comment by shinokada** [comment]
@zoltanszogyenyi Can you check this?

**Comment by jordigagomerino** [comment]
I saw on the website that you are also compatible with Tailwind 2. Is there a plan to deprecate this or should I look for a different aproach for this? Maybe something with props or some extra style classes?

**Comment by jordigagomerino** [comment]
Something new? It would be great if this is fixed. 
:)

**Comment by shinokada** [comment]
I suggest to take this issue to [Flowbite](https://github.com/themesberg/flowbite/issues).

**Comment by jordigagomerino** [comment]
Ok! Thanks @shinokada :)

**Comment by shinokada** [comment]
I close this for now. 
Thank you for your contribution.

**Pull request closed without merging**
