### PR TITLE
feat(maquee-component): New marquee banner component

### PR DESCRIPTION
**Pull request by vasucp1207**
Closes #

## Status

- [x] Not Completed
- [ ] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
The component should be under Extended since there is no same component in the main Flowbite.

**Comment by shinokada** [comment]
Thank you for your PR and I apologize for the late reply. Since there are quite few conflicts I have to create another branch to merge this.
It will be released soon with flowbite-svelte@0.44.13.
Thank you again for your contribution.
I close this PR for the above reason.

**Comment by shinokada** [comment]
@vasucp1207 Can you have a look at the following error in the dev tool console?

```
Marquee.svelte:22  Uncaught TypeError: Cannot read properties of null (reading 'offsetWidth')
    at Marquee.svelte:22:39
```

**Comment by vasucp1207** [comment]
@shinokada, can you open this PR I'm not able to make changes to this.

**Comment by shinokada** [comment]
@vasucp1207 Don't worry. I just fixed it. Thank you for your reply.

**Pull request closed without merging**
