### PR TITLE
ARIA Improvements for Dynamic Content

### PR DESCRIPTION
**Pull request by carsonmccue**
## 📑 Description
Adds some aria labels to dropdowns, tabs, and popovers to clarify what is happening with dynamic content for screen readers. These changes may not be necessary, but they might help provide users with screen readers clarity, so it does not hurt to add them. 

## ✅ Checks

- [ ✅ ] My pull request adheres to the code style of this project
- [❌] My code requires changes to the documentation
- [ ✅ ] I have updated the documentation as required
- [✅ ] I have checked the page with https://validator.unl.edu/
- [✅] All the tests have passed
- [ ✅] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information
Not sure what happened to the pnpm lock file. I think it is just because I am on an Apple device.

### CODE REVIEW

**Comment by shinokada** [comment]
`aria-expanded="true"` should be set when the dropdown is visible and `false` when it is hidden. So we can't set it always `true`.

**Comment by carsonmccue** [comment]
The element no longer exists in the DOM when aria-expanded is false, so we can leave it as true.

**Comment by shinokada** [comment]
Yes, you are right.

**Comment by shinokada** [comment]
@carsonmccue Can you solve the conflicts before merging?

**Pull request closed without merging**
