### PR TITLE
Fix radio checked attribute

### PR DESCRIPTION
**Pull request by andrewrisse**
## 📑 Description

The Radio  component does not check a radio button input by default when passing the checked prop.
This can be seen in the docs [here])(https://flowbite-svelte.com/docs/components/forms#Radio_buttons).
The Radio component has checked set to true, but it is not checked.

A radio group is defined by giving each of radio buttons in the group the same [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name). There is no "group" attribute for input  elements. ```bind:group``` was causing the checked attribute not to work.

## Status

- [ ] Not Completed
- [X] Completed

## ✅ Checks

- [ X ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ X ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed (could not get tests to run and didn't have time to mess with the config)
- [ ] My pull request is based on the latest commit (not the npm version).

## Summary by CodeRabbit

- **New Features**
	- Improved interaction model for radio buttons, allowing for more flexible state management within groups.

- **Bug Fixes**
	- Adjusted radio button functionality to enhance user input experience and state handling.

### CODE REVIEW

**Comment by mattdeboard** [comment]
For anyone else thumbing through pull requests and being nosy, here's a screenshot of the radio buttons that @andrewrisse referred to not working as intended in the docs . "Checked state" radio button should be checked since the `checked` prop is true.

image

**Comment by mattdeboard** [comment]
@andrewrisse Is there a workaround until this patch gets merged & released?

**Comment by shinokada** [comment]
It is working on the [site](https://flowbite-svelte.com/docs/components/forms#Radio_buttons). 
image

**Comment by mattdeboard** [comment]
So it is, interesting. Wonder if some underlying issue was resolved in svelte/kit et al.

**Pull request closed without merging**
