### PR TITLE
Class updates

### PR DESCRIPTION
**Pull request by shinokada**
## 📑 Description

- since we use `tailwind-merge`, we can remove all `custom` classes. This simplifies our API.
- use consistent propname. e.g. `$props.classOuter` for `outerClass` props
- update props
- add docs

## Status

- [x] Not Completed
- [ ] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by jjagielka** [comment]
You need to reapply my PR #845

**Comment by shinokada** [comment]
Thanks. I used the latest but somehow the old code was in. I don't know why.

I updated this part and it is fixed:

```
    'after:w-[9px] after:h-[9px] after:rotate-45 bg-inherit after:bg-inherit invisible after:visible after:block border-inherit after:border-inherit',
    position === 'top' && ($$props.border ? 'after:border-b after:border-r -bottom-[5px]' : '-bottom-[4px]'),
    position === 'bottom' && ($$props.border ? 'after:border-t after:border-l -top-[5px]' : '-top-[4px]'),
    position === 'left' && ($$props.border ? 'after:border-t after:border-r -right-[5px]' : '-right-[4px]'),
    position === 'right' && ($$props.border ? 'after:border-b after:border-l -left-[5px]' : '-left-[4px]')
```

**Comment by shinokada** [comment]
The bottom popover arrow color is not right.

image

**Comment by jjagielka** [comment]
Yes, top arrow issue was there from the beginning as is on Flowbite.com. The color is inherited from the background not from the title item. In the top position the title color should be set, but as user is free to chose whatever we would need to search for bg-* classes to apply to arrow. Not that straight forward.

**Pull request merged**
