### PR TITLE
feat: mdsvexample

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
Package `mdsvexamples` added. This allows to share the code and example html with only one copy.

Check the `alert.md` to see the difference.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information
There's a small bug in `msdexample` that prohibits the use of spaces in the meta variables. To overcome that I propose the workaround to glue class names with `underscore` and then unglue them in `ExampleWrapper.svelte`.

See `alert.md` to see that in practice.

### CODE REVIEW

**Comment by jjagielka** [comment]
Can you add me to the vercel.com configuration so I'd be able to see the failures myself?

**Comment by shinokada** [comment]
Great! 
I don't need to repeat it the same code twice.

**Comment by jjagielka** [comment]
What is the error on Vorcel?


Le sam. 10 sept. 2022 à 23:15, Shinichi Okada ***@***.***> a
écrit :

**Comment by shinokada** [comment]
Does it need to add script tag for each example?

**Comment by shinokada** [comment]
The only problem is that `import { whatever} from '$lib`.

`$lib` is confusing for users.

**Comment by jjagielka** [comment]
Yes you need to add script to each example but you can hide it.

And about the import from $lib I’ll find some workaround.


Le sam. 10 sept. 2022 à 23:23, Shinichi Okada ***@***.***> a
écrit :

**Comment by shinokada** [comment]
FYI:
As you noticed it about the new structure, I think it is much cleaner than `+page.md` with a folder.
The problem I found is that Toc. It shows the previous page Toc, etc.
I removed it for now.

I also removed the datepicker as well.

**Comment by shinokada** [comment]
> Can you add me to the vercel.com configuration so I'd be able to see the failures myself?

I will ask @zoltanszogyenyi .

But for now the errors are:

image

**Pull request closed without merging**
