### PR TITLE
Allows use of html in label, or alternately overwriting it entirely. …

### LINKED ISSUE #1092: allow for html in the label of a FloatingLabelInput
## Summary

I want to use icons in my labels.

### Basic example

```
<FloatingLabelInput label="<i class='fa fa-envelope'/> Email" />
```

### Motivation

It's a very simple change that allows more flexibility.  100% backwards compatible.

I'm wondering if I did a pr if it would get accepted?

### PR DESCRIPTION
**Pull request by kryptus36**
Closes #1092

### CODE REVIEW

**Comment by shinokada** [comment]
Why you need a named slot?

```
      {@html label}
```

or

```
   <slot>
      {@html label}
    </slot>
```

should be enough.

**Comment by jjagielka** [comment]
In fact it should be simply:
```svelte
<slot>{label}</slot>
```
and to make it even simpler we should remove the `label` prop from exports and use `<slot/>` for all labels. So instead of:
```svelte
<FloatingLabelInput style="filled" id="floating_filled" name="floating_filled" type="text" label="Floating filled" />
```
we would use that as:
```svelte
<FloatingLabelInput style="filled" id="floating_filled" name="floating_filled" type="text">
   Floating filled <span>containg html</span>
</FloatingLabelInput>
```

**Comment by kryptus36** [comment]
If you remove the label prop you break backwards compatibility.Naming the slot isn't strictly necessary. Let me know which solution is preferred and I'll update it. I was going for maximum flexibility.

**Comment by shinokada** [comment]
Please remove the label props and just add `<slot />`, since it is not a v1 yet.

**Comment by shinokada** [comment]
Can you update the markdown file for https://flowbite-svelte.com/docs/forms/floating-label as well?
The file is https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/docs/forms/floating-label.md.

**Pull request merged**
