### PR TITLE
feat: add double click event on tableBodyRow

### PR DESCRIPTION
**Pull request by gi4no**
## 📑 Description

add double click event to table body row component

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
Does this mean we need to add `dbclick` to other components too?

**Comment by shinokada** [comment]
Can you add an example to the https://flowbite-svelte.com/docs/components/table page using single click and double click?

**Comment by gi4no** [comment]
@shinokada 

I have added an example to the table page that demonstrates `on:click` and `on:dblclick` functionality. Please check it out and let me know if it meets your expectations. You can find the example in the documentation under the 'Click and double-click on row' section.

**Comment by shinokada** [comment]
Thanks for the PR! Excited for more from you in the future. 😄🚀

**Pull request merged**
