### PR TITLE
fix: add default value to opacity and space of paragraph element

### PR DESCRIPTION
**Pull request by seanwu1105**
## 📑 Description

Add default value to opacity and space of paragraph element. Thus, the user does not have to specify these properties for every `<P>` element.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
Can you run `npm run gen:props` and commit and push it again?
This will update the props automatically.

**Comment by shinokada** [comment]
We intentionally leave both props undefined for these lines:

```
(opacity && colorAndopacity) || (color && color)
...
space && spaces[space],
```

1. You **don't need** to specify these props. It is 100% and normal as the browser default.
2. If you specify it the above lines will break.

**Comment by seanwu1105** [comment]
I get the warning message without the default values. Maybe we can set the default values to `undefined`.

Screenshot from 2022-10-18 00-59-02
Screenshot from 2022-10-18 01-00-26

**Comment by shinokada** [comment]
The warnings come during the development. You can build it and check it again.

```
npm run build
npm run preview
```

**Comment by seanwu1105** [comment]
Though the warning disappears after build, I think it is still annoying to show the warning during development. Especially the paragraph element is really common to use and thus it's likely to generate a bunch of warnings polluting the consult during dev. It would be nice to avoid unnecessary messages.

**Pull request merged**
