### PR TITLE
feat: modal internal scrolling

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description

Add scrolling inside modal if content is too big to fit the space.

Partial solution to #311 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
The position of popup, form element modal are not centered.

image

image

**Comment by shinokada** [comment]
I see quite a few type warnings.
title, node, _open, etc.

**Comment by shinokada** [comment]
Let me know when you want me to merge.

**Comment by jjagielka** [comment]
It's ready to merge. Go on.

**Comment by shinokada** [comment]
Roger that.

**Pull request merged**
