### PR TITLE
Color & theming

### PR DESCRIPTION
**Pull request by shinokada**
## 📑 Description

- Update tailwind.config.cjs
- Add docs/pages/theming page

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
@jjagielka Can you have a look at this PS?

**Comment by jjagielka** [comment]
I don't know what you want to achieve with that approach. I've told that already I'm not a fan of `customBorder`, `customColor`, etc. It makes the API messy.

And in your example what is the difference between `custom` and `none`?
If you set `custom` and `customColor` you still loose the formatting for `border` and `text`. So why not to use `none` and `class`?

**Comment by shinokada** [comment]
There are some requests about custom colors on Reddit and on our issues.
I agree that it makes API messy.
I can remove that part. The main thing I wanted to achieve is how to modify colors and new default colors, `redfs`, etc in tailwind.config.cjs.

I'm not a fan of the Theme component as the [flowbite-react](https://flowbite-react.com/theme) team did. But it will be nice to have a page where users can change the color/theme.

If you have a better idea than theme page, I'm open to it.

**Comment by jjagielka** [comment]
I was thinking about it for some time, how to manage colors, but I'm still not ready to present the idea. Need some time more. I was busy with another work for the last two weeks. :)

**Comment by shinokada** [comment]
What do you think about my idea about adding custom colors to tailwind.config.cjs?

**Comment by jjagielka** [comment]
I think this is a way to do it, but we have to have a mechanism to get those definitions automatically implemented in the components.

**Comment by shinokada** [comment]
There are different approaches I can think of:

1. Theme/color page to explain how to modify tailwind.config.cjs manually (with examples)
2.  Flowbite-Svelte CLI to install pre-made custom colors from different options to modify tailwind.config.cjs
3. Similar to 2, but using scripts, `npm run theme theme-name` to modify tailwind.config.cjs

**Comment by shinokada** [comment]
Another way is to add `import` to the root `+layout.svelte`.

```
<script lang='ts'>
	import 'flowbite/flowbite-svelte-theme/styles/theme-name.css';
	import '../app.postcss';
</script>

<slot />
```

**Comment by jjagielka** [comment]
'flowbite-svelte-theme/styles/theme-name.css' is a user file?

**Comment by shinokada** [comment]
There are two ways I can think of.

1. Add a Theme.svelte with styles only. Users can import it in the `+layout.svelte` file.
2. Or create flowbite-svelte/styles/theme.css and users can import it in the `+layout.svelte` file.

**Pull request closed without merging**
