### PR TITLE
feat: checkbox more functions, changed API

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
Checkboxes re-written. 
- New simple API.
- Extra documentation
- Restructured layout
- No need for Label.svelte and Helper.svelte

Todo: Checkbox dropdown example.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit/version

## ℹ Additional Information
	https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Label

	To associate the <label> with an <input> element, you need to give the <input> an id attribute.
	The <label> then needs a for attribute	whose value is the same as the input's id.

	Alternatively, you can nest the <input> directly inside the <label>, in which case the for and
	id attributes are not needed because the association is implicit:

	<label>Do you like peas?
	<input type="checkbox" name="peas">
	</label>

### CODE REVIEW

**Comment by shinokada** [comment]
Thanks for the PR.
I think it is a developer's responsibility to add id for Label and Input components. We provided `{...$$restProps}`.

I just removed label and helper text from Input component.

I think current version suffices the need you brought up.

```
<Label for='input1'>Input 1</Label>
<Input id='input1' name='input1' />
<Helper>Bla bla bla.</Helper>
```

I think uses want flexible components.

What do you think?

**Comment by jjagielka** [comment]
I'm sorry but I don't understand your response.

In my PR the `{...$$restProps}` is passed to the input and you can set the name, id, etc.
I have even added a line at the `Props` section of the checkbox documentation stated that.

As for `id` I have copied you the extract from MDN in then Additional information above.

Versions
```html
<input id='input1>
<label for='input1>Label</label>
```
and
```html
<label><input>Label</label>
```
Setting `name` for `input` is still possible and `name` should not have to be the same as `id`. 
```html
<Checkbox id='input1' name='input1_name`>Label</Checkbox>
```
Check: https://stackoverflow.com/questions/1397592/difference-between-id-and-name-attributes-in-html

**Comment by jjagielka** [comment]
And by the way, the old way of doing things (as stated in the current version of the docs) will produce the same result while using my PR (I've just checked).

```html
<div class="flex">
  <div class="flex items-center h-5">
    <Checkbox id='helper-checkbox' aria-describedby="helper-checkbox-text" value='' />
  </div>
  <div class="ml-2 text-sm">
    <Label for='helper-checkbox'>Free shipping via Flowbite</Label>
    <Helper>For orders shipped from $25 in books or $29 in other categories</Helper>
  </div>
</div>
```

**Comment by jjagielka** [comment]
PR #157 addresses some concerns mentioned in that discussion. If #157 is approved this can be safely deleted.

**Pull request closed without merging**
