### PR TITLE
feat: mdsvexamples

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
Another attempt to add `mdsvexamples` to the project.

-  no need to duplicate code and example
-  import can now be `flowbite-svelte`
-  `mdsvexample` workaround with class not needed anymore
-  `alert.md` shows the advantage of that PR

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
Errors are:
image

**Comment by jjagielka** [comment]
Corrected. Seems it's finally works!

**Comment by shinokada** [comment]
The first alert has script tag.

image

But the second one doesn't.

image

I tried it with avatar page and the first one doesn't have the script tag.

image

```
```svelte example class="flex flex-col gap-4" hideScript
<script>
  import {Avatar} from 'flowbite-svelte'
</script>
<Avatar src="/images/profile-picture-2.webp" border/>
<Avatar src="/images/profile-picture-2.webp" border class="ring-red-400 dark:ring-red-300"/>
```
```

**Comment by shinokada** [comment]
Ok, I got it. the key is `hidescript`.

**Comment by jjagielka** [comment]
Yes. We can hide the `<script>` if it repeats on all the examples.

**Comment by shinokada** [comment]
Avatar User Dropdown is not working. 

```
```svelte example class="flex justify-center h-96" 
<script>
  import {Avatar, Dropdown, DropdownHeader, DropdownItem} from 'flowbite-svelte'
</script>

  <Avatar id="user-drop" src="/images/profile-picture-3.webp" dot={{color:'bg-green-400'}} />
  <Dropdown triggeredBy="#user-drop">
    <DropdownHeader>
      <span class="block text-sm"> Bonnie Green </span>
      <span class="block truncate text-sm font-medium"> name@flowbite.com </span>
    </DropdownHeader>
    <DropdownItem>Dashboard</DropdownItem>
    <DropdownItem>Settings</DropdownItem>
    <DropdownItem>Earnings</DropdownItem>
    <DropdownDivider />
    <DropdownItem>Sign out</DropdownItem>
  </Dropdown>
```
```

**Comment by jjagielka** [comment]
You've forgot to add `DropdownDivider` to script section.

**Comment by shinokada** [comment]
Thanks. I opens but doesn't close on my localhost. Build/preview works though.

**Comment by shinokada** [comment]
I updated all pages using this PR.
Thanks.

**Pull request merged**
