### PR TITLE
feat: Cards img improvements

### LINKED ISSUE #586: Cards with sized images
## Summary
**ETA**: PR submitted

Adding additional props to the Card component in order to define a size to its image.

### Basic example
**Before**
```js
<script lang="ts">
import { Card } from "flowbite-svelte"; 
export let project: { id: number };
</script>

<Card img="https://google.com/anyimg.png"} href={`/projects/${project.id}`} />
<Card img="https://google.com/anyimg2.png"} href={`/projects/${project.id}`} />
<Card img="https://google.com/anyimg3.png"} href={`/projects/${project.id}`} />
```

**After**
```js
<script lang="ts">
import { Card } from "flowbite-svelte"; 
</script>

<Card img="https://google.com/anyimg.png"} href={`/projects/${project.id}`} imgHeight={250} imgPosition='top' /*default */>
<Card img="https://google.com/anyimg2.png"} href={`/projects/${project.id}`} imgHeight={250} imgPosition='top' /*default */>
<Card img="https://google.com/anyimg3.png"} href={`/projects/${project.id}`} imgHeight={250} imgPosition='top' /*default */>
```
**Additional**: IMO a better implementation would be to add a typed parameter named `image` to the card, typed as
```
{
  url: string;
  height: number;
  position: 'top' | 'bottom' | 'left' | 'right' = 'top';
  fit: 'contain' | 'cover' | 'fill' | 'none' | 'scale-down';
}
```
but this would lead us **to deprecate** the use of `img` so I would like to get feedback on this.

### Motivation

Allow us to have uniform cards even when we can't or don't want to restrict images size

**Before**
Screenshot 2023-02-22 at 21-57-59 Screenshot

**After**
Screenshot 2023-02-22 at 22-17-17 Screenshot

### PR DESCRIPTION
**Pull request by LeBovin**
Closes #586

## 📑 Description
Cards images can be styled a bit more in order to being able to uniform the cards sizes.
Problem description and solution here can be found at #586

- [x] feature in itself
- [x] examples (md)

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information
**breaking change**: Cards img prop is now a type, not a single string.

### CODE REVIEW

**Comment by shinokada** [comment]
@jjagielka Can you have a look at this?

**Comment by jjagielka** [comment]
I get the reason, but I don't like the API change. For the default use we have to change from:
```svelte
<Card img="/images/image-1.webp" horizontal>
```
to
```svelte
<Card  img={{ url: '/images/image-1.webp', size: 'lg', position: 'top', fit: 'cover' }} horizontal>
```
So I'd propose either:
```js
  export let img: string | undefined = undefined; // img src
  export let imgFit: 'contain' | 'cover' | 'fill' | 'none' | 'scale-down' = 'contain';
  export let imgPosition: 'top' | 'bottom' | 'left' | 'right' = 'top';
```
or
```js
   export let img: string | ImageSettings | undefined = undefined;
   ...
   if (typeof img === 'string')
     img = { url: img, fit: 'contain', position:`top` }
```
---
**Note.** Please do not reformat the `card.md` file. The long lines are used on purpose. It's easier to understand example when unimportant code is hidden in overflow. Please compare the readability of:
```svelte
<Card>
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-2text-gray-500 dark:text-gray-400 "><path stroke-linecap="round" stroke-linejoin="round" d="M21 11.25v8.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5v-8.25M12 4.875A2.625 2.625 0 109.375 7.5H12m0-2.625V7.5m0-2.625A2.625 2.625 0 1114.625 7.5H12m0 0V21m-8.625-9.75h18c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125h-18c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" /></svg>
  <a href="/">
      <h5 class="mb-2 text-2xl font-semibold tracking-tight text-gray-900 dark:text-white">Need a help in Claim?</h5>
  </a>
  <p class="mb-3 font-normal text-gray-500 dark:text-gray-400">Go to this step by step guideline process on how to certify for your weekly benefits:</p>
  <a href="/" class="inline-flex items-center text-blue-600 hover:underline">
      See our guideline
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 ml-2"><path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" /></svg>
  </a> 
</Card>
```
versus
```js
<Card>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    stroke-width="1.5"
    stroke="currentColor"
    class="w-12 h-12 mb-2text-gray-500 dark:text-gray-400 "
    ><path
      stroke-linecap="round"
      stroke-linejoin="round"
      d="M21 11.25v8.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5v-8.25M12 4.875A2.625 2.625 0 109.375 7.5H12m0-2.625V7.5m0-2.625A2.625 2.625 0 1114.625 7.5H12m0 0V21m-8.625-9.75h18c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125h-18c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" /></svg>
  <a href="/">
    <h5 class="mb-2 text-2xl font-semibold tracking-tight text-gray-900 dark:text-white">
      Need a help in Claim?
    </h5>
  </a>
  <p class="mb-3 font-normal text-gray-500 dark:text-gray-400">
    Go to this step by step guideline process on how to certify for your weekly benefits:
  </p>
  <a href="/" class="inline-flex items-center text-blue-600 hover:underline">
    See our guideline
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="w-5 h-5 ml-2"
      ><path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" /></svg>
  </a>
</Card>
```

**Comment by jjagielka** [comment]
On the second thought I think this is a wrong direction. We should not complicate the API.
If we need to add advanced image management, then simply adding the slot around the background img would do the trick:
```svelte
  {#if img}
     <slot name="img">
      <img class={imgClass} src={img} alt="" />
     </slot>
    <div class={innerPdding}>
      <slot />
    </div>
  {:else}
```
Then you can use it as:
```svelte
<Card>
  <img slot="img" class="object-fill object-left w-13 h-10" src="...." />
  The card internal text.
</Card>

**Comment by LeBovin** [comment]
Hello @jjagielka,
Thank you for your answers.
I agreed with your first feedback:

> I get the reason, but I don't like the API change. For the default use we have to change from:
> 
> ```svelte
> <Card img="/images/image-1.webp" horizontal>
> ```
> 
> to
> 
> ```svelte
> <Card  img={{ url: '/images/image-1.webp', size: 'lg', position: 'top', fit: 'cover' }} horizontal>
> ```
> 
> So I'd propose either:
> 
> ```js
>   export let img: string | undefined = undefined; // img src
>   export let imgFit: 'contain' | 'cover' | 'fill' | 'none' | 'scale-down' = 'contain';
>   export let imgPosition: 'top' | 'bottom' | 'left' | 'right' = 'top';
> ```
> 
> or
> 
> ```js
>    export let img: string | ImageSettings | undefined = undefined;
>    ...
>    if (typeof img === 'string')
>      img = { url: img, fit: 'contain', position:`top` }
> ```

As stated on the initial issue, I was a bit worried about involving a breaking change. At the end, your second implementation looks like the best one to me. It forces people to follow the Flowbite card's guidelines: rounded card with full width (full height with horizontal option) etc.

So, given this last point, I'm not a fan of your last proposal. As a terrible UI decision-maker, I use UI library such as Flowbite in order to be forced to use the objects as they have been designed and this prevents me to make horrible UIs.
IMO, your last proposal break this principle as I will have to redefine every classes that were defined before, only to get an image cropped as I want to

**Comment by LeBovin** [comment]
@jjagielka Hello,
any feedback?

**Comment by jjagielka** [comment]
You're right that the slot solution would require a bit of manual reformatting of the image.
With that in mind, you're free to update your proposed PR with the solution two: 

```svelte
<script>
  export let img: string | ImageSettings | undefined = undefined;
</script>
```

**Comment by shinokada** [comment]
Is this PR ready to be merged? Let me know.

**Comment by shinokada** [comment]
@jjagielka Can you review this PR?

**Comment by shinokada** [comment]
@LeBovin Thank you for your PR. Since we have changed from classnames to tailwind-merge and a new layout, this PR is outdated. Please create a new PR if you think this change is necessary with a detailed description.
I close the issue for now.

**Pull request closed without merging**
