### PR TITLE
New Component: MultiSelect

### PR DESCRIPTION
**Pull request by vasucp1207**
Closes #

## 📑 Description

An initial version of multi-select component https://github.com/themesberg/flowbite-svelte/issues/50.

multi-select

## Status

- [x] Not Completed
- [ ] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by vasucp1207** [comment]
@shinokada, what are your thoughts on this?

**Comment by shinokada** [comment]
Thank you for your PR. It looks good.
Can you put your example after [Select input example](https://flowbite-svelte.com/docs/forms/select#Select_input_example) rather than having a separate page? I think it is a better place for users.

**Comment by vasucp1207** [comment]
> Thank you for your PR. It looks good. Can you put your example after [Select input example](https://flowbite-svelte.com/docs/forms/select#Select_input_example) rather than having a separate page? I think it is a better place for users.

Made the necessary changes check now.

**Comment by shinokada** [comment]
Thank you for adding this new component with its new features to the project. 
Your contribution is greatly appreciated and will help improve the project. 
Great work and keep it coming.

**Comment by shinokada** [comment]
Can you start using the [Conventioal commit](https://www.conventionalcommits.org/en/v1.0.0/) when you write a commit comment?

Please use `fix:`, `feat:`, `chore:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`, etc.

**Comment by vasucp1207** [comment]
Ok, I will take care of this from now.

**Comment by shinokada** [comment]
Since you are the author of Multi Select, please join [this](https://github.com/themesberg/flowbite-svelte/pull/847) conversation.

**Pull request merged**
