### PR TITLE
Fix: Disabled Button 

### PR DESCRIPTION
**Pull request by tommygiesbrecht**
Closes #

## 📑 Description

The `disabled` attribute is not applied to the button.

## Status

- [x] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
I intentionally removed it. 
Please see https://github.com/themesberg/flowbite-svelte/issues/1328.

**Comment by tommygiesbrecht** [comment]
The button has no attribute `disabled`. So my test cases failed because I can't check if the button is disabled. Maybe can add `disabled={true}` instead of `{...$$restProps}`

**Comment by jbraswell** [comment]
Would love to see this fixed. As it stands, it seems impossible to disable a form's submit button without hacking around this bug. Has anyone found a clean workaround?

**Comment by shinokada** [comment]
@jbraswell It is already fixed. If you have any problems, please create a new issue. Thanks.

**Pull request closed without merging**
