### PR TITLE
Change hard coded classes to exports class

### PR DESCRIPTION
**Pull request by vasucp1207**
Closes #

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
Can you hold this? We are having a discussion about how much we should expose CSS to users at the moment.

**Comment by vasucp1207** [comment]
> Can you hold this? We are having a discussion about how much we should expose CSS to users at the moment.

Ok, no problem let me know the required changes when you conclude this.

**Comment by shinokada** [comment]
@jjagielka Following our discussion on Discord, I would like to request your permission to merge this PR. Please let me know if you have any concerns or if there is anything else I need to do before proceeding.

**Comment by shinokada** [comment]
Thank you for your contribution! 
I appreciate your effort in helping to improve our project. 
However, I will be closing this issue in favor of the approach outlined in https://github.com/themesberg/flowbite-svelte/pull/840. 
Please feel free to continue contributing to our project in the future. 😊

**Pull request closed without merging**
