### PR TITLE
feat: popper old style

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
`Popper` back to Flowbite.com compliant implementation using the `visibility` and `opacity` classes.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information
This should prevent the issue on some `dev` runs.

### CODE REVIEW

**Comment by shinokada** [comment]
- dropdowns#Programatic_open/close page has a wrong offset
 
image

**Comment by shinokada** [comment]
npm run build and npm run preview works.
But local host on Chrome/Brave/Safari gives the following console errors. (different from the previous)

image

**Comment by jjagielka** [comment]
Thanks. Let me take a look at those.

**Comment by jjagielka** [comment]
In the `src\routes\dropdowns\+page.md` remove the open by default variable `let dropdownOpen = false;` and see if you still have that error, please.

**Comment by shinokada** [comment]
Line 35
```
 let dropdownOpen = false;
```

image

**Comment by shinokada** [comment]
What does "Popper back to Flowbite.com compliant implementation using the visibility and opacity classes." in your PR description mean?
I'm not sure why you have created this PR.

**Comment by jjagielka** [comment]
This is the implementation that uses setting classes on the popper content: `class={open? 'visible opacity-100': 'invisible opacity-0'}` Flowbite.com do that in their js files.

I have created that to check if that removes the issue you're facing with the previous, more svelte like, implementation of using the `{#if}` directive.

You can leave that PR unmerged and treat that as battle field for further tries.

**Comment by shinokada** [comment]
Thank you for the clarification.

**Pull request closed without merging**
