### PR TITLE
feat: add step indicator component

### PR DESCRIPTION
**Pull request by carstenlebek**
## 📑 Description

Added a step indicator component.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information

Couldn't get the Nu HTML Checker to run. Should be alright though.

### CODE REVIEW

**Comment by shinokada** [comment]
Thank you for your PR.
Where can I find this component at Flowbite.com?

**Comment by carstenlebek** [comment]
You can't right now. It wasn't mentioned in the contributing guidelines, that the components have to be available in the core Flowbite repo. I was just building the component in a project I use Flowbite Svelte with and was thinking it could be a great addition to the library. 

However I could create a PR on Flowbite to add the component to the core library too.

**Comment by shinokada** [comment]
Please  do it so.

**Comment by shinokada** [comment]
I think I will add this under EXTEND menu. What do you think?

**Pull request merged**
