### PR TITLE
feat: Improve Carousel, additional styling options, mixed image size support

### PR DESCRIPTION
**Pull request by jsonMartin**
## 📑 Description
There are many parts of the Carousel component that aren't exposed, and thus it is not possible to style every aspect of the Carousel's DOM; this makes it difficult to alter styling of certain elements such as thumbnails or the `img` element. 

Also, the current Carousel doesn't work well when images are different sizes. This PR adds features exposing previously hidden DOM element classes for more control, and improves support for mixed image sizes. 

Here's a summary of additions:
- Adds Image Class functionality (`img` element styling & enables animations at the `img` level by wrapping in `{#key}`)
- Adds `imgFit` prop which allows for setting `object-fit`, allowing for displaying entire image in Slide `contain` or filling entire slide with `cover` (default)
- Adds `thumbClass` (Thumbnail Wrapper, allows for controlling opacity etc)
- Adds `thumbDivClass` (Thumbnail Div, allows for changing color and grid layout)
- Adds `thumbBtnClass` (Tumbnail Button element styling, allows for mouseover effects)
- Adds `transitionDivClass` (Transition Wrapper Element styling support)
- `slideClass` has added Tailwind Merge support

Here's a live example (loads random gallery images on every page load to test different image sizes): [https://flowbite-gallery-example.netlify.app/](https://flowbite-gallery-example.netlify.app/)

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information
Here's a live example (loads random gallery images on every page load to test different image sizes): [https://flowbite-gallery-example.netlify.app/](https://flowbite-gallery-example.netlify.app/)

### CODE REVIEW

**Comment by shinokada** [comment]
Thank you for your PR.
Can you put the types back?

For example:

```
export let divClass = 'overflow-hidden relative h-56 rounded-lg sm:h-64 xl:h-80 2xl:h-96';
// should be
export let divClass: string = 'overflow-hidden relative h-56 rounded-lg sm:h-64 xl:h-80 2xl:h-96';
```

**Comment by jsonMartin** [comment]
> Thank you for your PR. Can you put the types back?
> 
> For example:
> 
> ```
> export let divClass = 'overflow-hidden relative h-56 rounded-lg sm:h-64 xl:h-80 2xl:h-96';
> // should be
> export let divClass: string = 'overflow-hidden relative h-56 rounded-lg sm:h-64 xl:h-80 2xl:h-96';
> ```

Good catch @shinokada! I must not have noticed this because my IDE automatically adds inline Typescript annotations, and no errors were being thrown because it was inferring the type from variable declarations 😄 

Sure thing, I just added the missing types and pushed up the changes 👍🏼

**Comment by jsonMartin** [comment]
Also, I just realized after taking a look at the code one more time that the `imgFit` prop was only on `Carousel`, but not the `CarouselTransition` component. 

The latest commit now also adds `imgFit` prop to `CarouselComponent`

**Comment by shinokada** [comment]
Is it possible the dark mode class for the custom styling bg class? 

image

**Comment by jsonMartin** [comment]
Sure, just added the dark mode background class and pushed up the changes.

Here's what it looks like now in dark mode:
CleanShot 2023-08-05 at 21 16 24@2x

**Comment by shinokada** [comment]
I noticed that when you hover tooltips like github, dark-mode, the screen goes upwards.

https://github.com/themesberg/flowbite-svelte/assets/147320/8eae07ec-fcb7-4ea1-a573-8ddb329c9a23

**Comment by shinokada** [comment]
I will manually pull your request and merge them.

**Comment by shinokada** [comment]
Since I had difficulties in merging this PR, I have merged it manually at https://github.com/themesberg/flowbite-svelte/commit/f809b63400143255ca56e77d6ff0806c797cbc50.
Thank you for your contribution. I'm looking forwards to seeing more in the future.
I close this PR for now.

**Comment by jsonMartin** [comment]
Great, thanks for merging in the changes 👍

BTW, I just checked out the live example and I don't see the hover bug happening on my end; I'm guessing you were able to fix it @shinokada?

However, when checking the hover, I did notice another bug - not on a component page but on the _homepage_. I don't see it happen when the scroll position is at the top of the page, but otherwise when mousing over one of the tooltip social icons, it scrolls the page down:

https://github.com/themesberg/flowbite-svelte/assets/4033621/5ad9c544-87c5-4efa-a9fa-1c40f6b802fd

I'll go ahead and open a new issue for this homepage hover bug

**Comment by shinokada** [comment]
@jsonMartin After adding swipeable by @minervabot-main, the custom style section lost what you had.
Can you check it and creat a PR, please?

**Comment by jsonMartin** [comment]
> @jsonMartin After adding swipeable by @minervabot-main, the custom style section lost what you had.
> Can you check it and creat a PR, please?

Hi @shinokada , sure, I will check it out when I get a chance.

The rest of my week is packed though so I probably won't be able to get to this until next week

**Comment by jsonMartin** [comment]
> @jsonMartin After adding swipeable by @minervabot-main, the custom style section lost what you had. Can you check it and creat a PR, please?

Hi @shinokada , I just created a PR to fix this at: https://github.com/themesberg/flowbite-svelte/pull/1023

**Pull request closed without merging**
