### PR TITLE
Fixed more typos and website layout

### PR DESCRIPTION
**Pull request by Hetarth02**
## 📑 Description
Fixed small typo in `Getting Started` and `How to Contribute` pages of the documentation.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit/version

### CODE REVIEW

**Comment by Hetarth02** [comment]
As I go through documentation, I will try to find and edit the typos I find but it will take me some time in doing this.

**Comment by shinokada** [comment]
Thank you for finding the typos. 
Can you push more commits to this PR when you find the typos?
I will then merge it.
Thanks again.

**Comment by Hetarth02** [comment]
Sure will do.

**Comment by Hetarth02** [comment]
I have fixed the website layout somewhat after reviewing your changes. Here is a before-after comparison,

> Before, the entirety of the content was not showing(especially in footer) even after your changes.

image

image


> After, now it is much more breathable and the content is fully visible.

image

image

@shinokada You can merge these changes for now as currently the website somewhat hinders user's readability, I will open a new PR which will contain fixed typos.

Hope you find these changes helpful!

**Comment by shinokada** [comment]
Thanks. Merged to v0.22.10.

**Comment by shinokada** [comment]
Ok, it is successfully deployed. Thank you for the PR.

**Comment by shinokada** [comment]
image

I think there is too much padding on the left than right for the main.
Can you have a look at this?

**Comment by Hetarth02** [comment]
Yeah, sure. Let me check and update you on this.

**Comment by shinokada** [comment]
macOS Monterey, version 12.4
Brave, Chrome, and FF.

**Comment by Hetarth02** [comment]
I rechecked my code, but I couldn't find anything. I think the issue might be regarding responsiveness on large screens(large screens as defined by tailwind). I think the issue might be originating from this bit.

[Commit Link](https://github.com/themesberg/flowbite-svelte/commit/79f7395e889a3bac1697c9fd294d64541cf8d9d7)

image

Can you try changing the `lg:pl-80` to something smaller like `lg:pl-32` or `lg:pl-48`. I hope this would fix the issue.

**Comment by shinokada** [comment]
Ok, thanks. I will do it.

**Comment by shinokada** [comment]
Can you try the following in your system?

```
<main class="flex mx-auto mb-8 px-2 pt-16 lg:pl-72 2xl:pl-32">
```

And let me know.

**Pull request merged**
