### PR TITLE
fix: correction in using style and color

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
Update in usage of the `color` property.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
I'm not fond of changing app.css. It may affect somewhere in the doc.

**Comment by jjagielka** [comment]
Currently each component docs contains that at the bottom of the page:
```html
<Htwo label="Props" />

The component has the following props, type, and default values. See <a href="/pages/types">types 
 page</a> for type information.
```
and the link to types is completely indistinguishable from the rest of the text.

**Comment by shinokada** [comment]
I can fix these.

**Comment by jjagielka** [comment]
OK. I have removed the changes from `app.css`.

**Comment by shinokada** [comment]
Strange. When I save the app.css, `dark:something` becomes `dark: something` and tests fail. 
Do you know it is something to do with prettier?

**Comment by jjagielka** [comment]
I don't know. I can see that `.prettierrc` has an entry `"embeddedLanguageFormatting": "auto",`. Can that make a strange behavior?

**Comment by shinokada** [comment]
I add a file association in the settings editor (File > Preferences > Settings) under Text Editor > Files. Enter *.css for the item, and tailwindcss for the value. 
Then it works now.

**Comment by shinokada** [comment]
Merged.

**Comment by shinokada** [comment]
I don't know why this is still in the PR. It should be closed since I just merged.

**Pull request merged**
