### PR TITLE
fix: Multiselect interactivity and form bug fixes

### PR DESCRIPTION
**Pull request by bentilling**
### UI fixes
- Added background colour on light mode to avoid see though drop down
- Only show clear all icon when at least one element selected
- Fixed bug where clicking in the gap between the items in the dropdown closes the menu
- Fixed bug where the dropdown is cropped by other divs and modals
- Reversed chevron direction when dropdown open
- Added additional contrast when text hovered/selected

### Form fixes
- Clicking the chevron no longer submits a form
- Added a hidden html multi-select with bound values for form actions

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by bentilling** [comment]
I didn't want to make any breaking changes in this PR but if wondering what the maintainers think of the additional suggestions as a follow up

1. Changing the
`value: (string | number)[]`  prop to `selected: SelectOptionType[]`

As the items prop is already `SelectOptionType[]` this keeps the prop types consistent and simplifies the component which is currently keeping two vars representing the same info in sync.

2. Removing (or make optional) custom events from inside the component.

Imo we do not want to force action events for those that simply want to bind to the value or use as a form. I suggest we either remove and let the parent component fire an event off the bound `selected` or alternatively we could add a prop like eventType: (string | null) which we use to optionally setup with a custom type (as at the moment they are all firing the same “selected” event which could cause issues if multiple multi-selects exist).

Let me know your thoughts or if better to move this discussion elsewhere!

**Comment by hamboomger** [comment]
> Clicking the chevron no longer submits a form
Without this I can't use Multiselect on production, thank you for fixing that! Hope this PR will get merged soon...

**Comment by bmccorm2** [comment]
Thank you for fixing this this!!  Looking forward to the merge.
`Added a hidden html multi-select with bound values for form actions`

**Comment by bentilling** [comment]
Thanks both, @hamboomger yes this also fixes the transparent issue. 

@shinokada is there anything you want me to address in this before it is ready to merge?

**Comment by shinokada** [comment]
- [Line 26](https://github.com/themesberg/flowbite-svelte/blob/fe465cb8550d281fc664f0250ec2264d20514ef9/src/lib/forms/MultiSelect.svelte#L26C9-L26C25): Can you change the quote to single, not back-tick.

- [LIne 84](https://github.com/themesberg/flowbite-svelte/blob/fe465cb8550d281fc664f0250ec2264d20514ef9/src/lib/forms/MultiSelect.svelte#L84) change `twJoin` to `twMerge` so that `$$props.class` can overwrite `multiSelectClass`.

**Comment by shinokada** [comment]
Thank you for your contribution.

**Pull request merged**
