### PR TITLE
Megamenu

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
Mega menu component.

`<Megamenu/> is a standard visible component and its floating and visibility is managed by the `<NavDropdown/>`.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit/version

## ℹ Additional Information
I've tried to add all the necessary links, declarations, types, etc., but probably I've missed something.

There's a strange error and the doc page `megamenu/index.md` gets narrower then expected from time to time. I don't know how to fix that.

### CODE REVIEW

**Comment by shinokada** [comment]
Thank you for the PR.
1. Can you check the position for the default mega menu and the mega menu with icons?

Flowbite
image

Flowbite-Svelte
image

Flowbite
image

Flowbite-Svelte
image

2. Menu item style

Flowbite
image

Flowbite-Svelte
image

Menu items in a mega menu li should not have the class but li>a should have the class `hover:underline hover:text-blue-600 dark:hover:text-blue-500`.

**Comment by jjagielka** [comment]
Should be good to run `npm run gen:props` to refresh all the recent changes.

**Comment by shinokada** [comment]
Thank you for the fix. Merged.

**Comment by shinokada** [comment]
Added `megamenuLayout`, `megamenuBlock` and updated the props.
Please set `export` variables at the top, before a function.

Thank you for your hard work.

**Comment by shinokada** [comment]
@jjagielka Thank you for your continuous contribution. Your contribution is a great help.

Is it possible to inform the component you want to  work by adding a short comment in the issue?
Then we can avoid duplicate work.

- https://github.com/themesberg/flowbite-svelte/issues/176
- https://github.com/themesberg/flowbite-svelte/issues/11
- https://github.com/themesberg/flowbite-svelte/issues/168
- https://github.com/themesberg/flowbite-svelte/issues/76
- https://github.com/themesberg/flowbite-svelte/issues/51
- https://github.com/themesberg/flowbite-svelte/issues/50
- https://github.com/themesberg/flowbite-svelte/issues/49
- https://github.com/themesberg/flowbite-svelte/issues/29
- https://github.com/themesberg/flowbite-svelte/issues/6

**Comment by shinokada** [comment]
@jjagielka Can you have a look at this issue?
Mega menu is centered in a small screen.

[Flowbite](https://flowbite.com/docs/components/mega-menu/#mega-menu-with-icons)
image

http://localhost:8000/mega-menu#Mega_menu_with_icons
image

**Comment by shinokada** [comment]
@jjagielka Can you have a look at `item` type error?

image

**Comment by shinokada** [comment]
A11y problems with mega-menu page.


https://validator.unl.edu/?showsource=yes&showoutline=yes&doc=https%3A%2F%2Fflowbite-svelte.com%2Fcomponents%2Fmega-menu#cl307c338

**Pull request merged**
