### PR TITLE
feat: home page cta

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
CTA element for the Home Page

## Status

- [ ] Not Completed
- [x] Completed

Content is copied directly from Figma but it looks like a temporary one.

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka,

I've updated some spacings and the content.

It would be cool to make the dark / light mode switcher `<button>` and make them interactive - meaning they should toggle dark and light mode just like the button does in the navbar.

After that I'll check it out once again and I think it'll be good to merge.

Great job!

Cheers,
Zoltan

**Comment by jjagielka** [comment]
@zoltanszogyenyi - done, please check.

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka,

Works great! Just one more thing - it would be nice if the dark mode button (with the moon) will become active (ie. orange/primary color) and the light mode becomes inactive when switching over and back and forth.

For example when dark mode is active then the moon button should be orange and the light button gray and same thing applies for when light mode is active.

Screenshot 2023-04-27 at 15 34 53

Then I think we can merge it for sure.

Cheers,
Zoltan

**Comment by jjagielka** [comment]
I've made it the other way. When the dark is selected, the light button is orange to attract clicking. In light mode, dark button gets the look. I can swap it back if you disagree with that.

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka,

Thanks for the update - yeah I think we should reverse it.

Light mode active: sun button orange, moon button grey
Dark mode active: moon button orange, sub button grey

And one more thing -> only the gray button should be clickable because that's the one you can switch to, clicking the same theme mode has no sense because it shouldn't change anything. For example, I'm in dark mode, there's no need to click on dark mode again.

Hope it makes sense!

**Comment by shinokada** [comment]
Please update the status when it is ready for merge.

image

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka @shinokada,

Works great - it's ready to be merged <3

Cheers,
Zoltan

**Pull request merged**
