### PR TITLE
feat: toast fine tune

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
`Toast` to use more standard naming:
- `visible` changed to `open`
- `postition` changed from `tr|tl|br|bl` to `top-left|top-right|bottom-left|bottom-right`

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
For your note: I found that `npm run gen:props` doesn't pick up a prop if you have a comment above.
I removed the comment and it added a new prop to Toast compo.

**Comment by shinokada** [comment]
Toast transition examples are not working.

**Comment by jjagielka** [comment]
PR #363 - added `local` to transition function in `Frame`.

This kills transitions on `Toast`. It's enough to remove #363 to make them work again.

**Comment by shinokada** [comment]
Ok, got it.

**Pull request merged**
