### PR TITLE
fix: Added z-50 to dropdown container so it always stays on top

### LINKED ISSUE #897: Dropdown z-index issue.
### Describe the bug

Hi there,

I've noticed an issue In the most recent update when using the Dropdown component.

Previously the Dropdown would float as expected over the top of  any Tables directly below.

Now after the update the Dropdown is now floating beneath any Tables. (See attached screenshot)

it appears a z-index might be missing from the resultant HTML.

Cheers,
Matt

Screenshot 2023-07-06 at 4 33 24 PM

### Reproduction

```
  <Button><Chevron>Actions</Chevron></Button>
  <Dropdown>
    <DropdownItem href="/somelink">Somelink</DropdownItem>
    <DropdownItem href="/somelink">Somelink</DropdownItem>
  </Dropdown>

<Table shadow={true} hoverable={true}>
  <TableHead>
    <TableHeadCell>Name</TableHeadCell>
  </TableHead>
  <TableBody tableBodyClass="divide-y">
    <TableBodyRow>
      <TableBodyCell>No tags</TableBodyCell>
    </TableBodyRow>
  </TableBody>
</Table>
```

Resulting HTML:

```
<button type="button" class="text-center font-medium focus:ring-4 focus:outline-none inline-flex items-center justify-center px-5 py-2.5 text-sm text-white bg-primary-700 hover:bg-primary-800 dark:bg-primary-600 dark:hover:bg-primary-700 focus:ring-primary-300 dark:focus:ring-primary-800 rounded-lg">Actions <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" class="h-4 w-4 ml-2" aria-label="chevron down" fill="none" viewBox="0 0 20 20" role="img" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7" stroke="currentColor"></path></svg></button>  

<div tabindex="-1" class="bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-200 rounded-lg border-gray-100 dark:border-gray-700 shadow-md outline-none divide-y divide-gray-100 dark:divide-gray-600" role="tooltip" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(988px, 216px);" data-popper-placement="bottom"> <ul class="py-1 w-44">
<li><a href="/somelink" class="font-medium py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 block">Some link</a></li> 
<li><a href="/somelink" class="font-medium py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 block">Some link</a></li> 
</ul>  
</div>
```

Table HTML omitted...

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) x64 Apple M1
    Memory: 125.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/opt/node@18/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.7.2 - ~/Projects/example/node_modules/.bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.21.0 
    flowbite-svelte: ^0.39.0 => 0.39.2 
    svelte: ^4.0.0 => 4.0.4 
    vite: ^4.0.0 => 4.3.9
```

### LINKED ISSUE #939: Using a `Dropdown` within a `Listgroup` does not seem to have correct `z-index`
### Describe the bug

When using a `Dropdown` within a `Listgroup` depending on the direction the dropdown tries to open it goes BELOW the list and therefore makes it impossible to select options. It seems like that no (or at least not a correct) `z-index` is applied to the outer most menu container.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-cfdpkz?file=src%2Froutes%2F%2Bpage.svelte

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 18.34 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.6.8 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 114.1.52.130
    Chrome: 114.0.5735.198
    Edge: 113.0.1774.57
    Safari: 16.3
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.22.3
    flowbite-svelte: ^0.40.1 => 0.40.1
    svelte: ^4.0.5 => 4.0.5
    vite: ^4.4.2 => 4.4.4
```

### PR DESCRIPTION
**Pull request by fkrauthan**
Closes #939 
Closes #897

## 📑 Description

Added `z-50` to the dropdown container so it always stays on-top of all elements (e.g. no longer hidden behind a `ListGroupitem`.

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
If you set it `z-50` and scroll up to the navbar, then it may cover the navbar. How about `z-40`?
Or we can export it?

**Comment by fkrauthan** [comment]
But wouldn't that be actually preferred? A dropdown should always be visible so I can select options?

**Comment by fkrauthan** [comment]
@shinokada but please let me know if you feel strongly about changing it to `z-40`. You actually suggested `z-50` in your reply of #897

**Comment by shinokada** [comment]
If you set `z-50`, this will happen:

image

**Comment by shinokada** [comment]
How about this approach?

```
<script>
// more lines
export let divClass: string = 'divide-y';
// more lines
</script>

<Popper activeContent {...$$restProps} class={divClass} on:show bind:open>
```

So that users can change the `divClass` by adding whatever they want.

**Comment by shinokada** [comment]
That's fine. Can you add `Use the classContainer prop to overwrite containerClass.` to the docs?

**Comment by fkrauthan** [comment]
Oh yeah done :)

**Pull request merged**
