### PR TITLE
docs(multi select): update content for docs

### PR DESCRIPTION
**Pull request by zoltanszogyenyi**
## 📑 Description

I've added some extra content to the docs for multi select, but we should also use this PR to improve the styles based on the Flowbite Figma Design System - here's how it should look for the input element itself:

Screenshot 2023-06-10 at 14 43 50

I've talked with @robert1508 to also help us with some designs for the dropdown select itself too.

Here is the link to the forms / tags input component: https://www.figma.com/file/d2RLQMdSBhlzMT40ovcDJf/Flowbite-Design-System?type=design&node-id=3279%3A34618&t=Oqh5WRDxLIVmeRCE-1

Alternatively, we can use the Autocomplete dropdown styles from here: https://www.figma.com/file/d2RLQMdSBhlzMT40ovcDJf/Flowbite-Design-System?type=design&node-id=101%3A14547&t=Oqh5WRDxLIVmeRCE-1

Screenshot 2023-06-10 at 14 47 28

## Status

- [x] Not Completed
- [ ] Completed

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

@jjagielka @shinokada would need a bit of help with the coding of the design here, the component is awesome in itself

### CODE REVIEW

**Comment by jjagielka** [comment]
With pleasure, but I'm away for a week now. So you'll need to wait for me.

**Comment by shinokada** [comment]
I can't access the Figma file.

**Comment by robert1508** [comment]
I managed to finish the design for the dropdown select menu, 
you can find them here: https://www.figma.com/file/R1dsLLkZHGdkoukGVWllrg/flowbite-pro-figma-v2.6.0?type=design&node-id=3279%3A34618&t=niA92RBlRjGIgRy7-1

Screenshot 2023-06-12 at 15 27 37

**Comment by jjagielka** [comment]
@robert1508 two points:
- this is **select** component so it should look like a normal select when empty, shouldn't it? Do we need the `chevron down` at the right end?
- as this is multiple options it's often implemented with `clear all` button. So additional `x` somewhere? The right end, again?

**Comment by shinokada** [comment]
@vasucp1207 Do you have time to help with this PR?

**Comment by jjagielka** [comment]
What's left in that? I have updated the `MutliSelect` few days ago #875, so it looks like in Figma. Do you see any missing features?

**Pull request closed without merging**
