### PR TITLE
Cards

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
Cards module re-written. Previously `Card` component was too specialized with all those headers, texts, etc.
Currently it's up to the user to manage the text space.

Several examples updated / added. Some examples like e-commers, login, price should not be here as too complicated and they should be rather part of the `blocks` section.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit/version

### CODE REVIEW

**Comment by shinokada** [comment]
Thank you for the PR.

Can you look at the following points?

Card API change breaks https://flowbite-svelte.com/accordions, https://flowbite-svelte.com/cards, https://flowbite-svelte.com/carousels, https://flowbite-svelte.com/forms, https://flowbite-svelte.com/modals, https://flowbite-svelte.com/ratings, https://flowbite-svelte.com/tabs, and https://flowbite-svelte.com/timelines.

https://flowbite-svelte.com/accordions
image

PR
image

**Comment by shinokada** [comment]
Thanks. I will merge it soon and I will fix index pages.

**Comment by shinokada** [comment]
When I use 4 starts for E-commerce card, the last star size is different from others.

image

**Comment by jjagielka** [comment]
This is feature of ‘svelte-heros’ package. Icons in solid variant are smaller then the outline ones. 
Anyway, Card component uses the Rating component to render the stars. It has to e managed there.

**Comment by shinokada** [comment]
Thank you for the reply. I will have a look.

**Comment by shinokada** [comment]
You may notice this but I updated svelte-heros and the problem is solved.
https://github.com/shinokada/svelte-heros/commit/ccf3c22a001831aaa159ab974288fdc8d17ba7b2

**Pull request merged**
