### PR TITLE
fix: navbar updates

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
Navbars in Flowbite.com have changed. Especially in mobile view.

This PR
- tries to bring the compatibility with above changes
- uses `Frame` to implement navbar components
- adds few examples to navbar docs
- some other non-navbar tweaks 
 - `Dropdown` color and border fine tune
 - `DropdownItem` to be `<a>` and remove of `tabindex`

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
- [ ] User menu dropdown 

The position is wrong before and after click in a small screen.

image

- [ ] Navbar with search

When you click the search icon, nothing happens.

image

- [ ] Default mega menu

The `ExampleDiv` needs more height in mobile version.

image

- [ ] Maga menu with icons

Same as above. It needs more height.

- [ ] Full width dropdown

image

And in a normal screen, it breeds out of the `ExampleDiv` container. May you need to add `relative` to parent?

-[ ] Full width with CTA

Same as above.

And in a normal screen, it breeds out of the `ExampleDiv` container. May you need to add `relative` to parent?

- [ ] Full width with image

Same as above.

And in a normal screen, it breeds out of the `ExampleDiv` container. May you need to add `relative` to parent?

image

**Comment by jjagielka** [comment]
- [x]    User menu dropdown:  position is wrong before and after click in a small screen. 
- [ ]     Navbar with search: When you click the search icon, nothing happens.
 What should happen? Nothing happens in previous version nor on Flowbite.com
- [x]     Default mega menu: The ExampleDiv needs more height in mobile version.
- [x]     Maga menu with icons: as above. It needs more height.
- [ ]     Full width dropdown: And in a normal screen, it comes out of the ExampleDiv container. May you need to add relative to parent?
 This is a `popperjs` workaround. There is already `relative` in the parent element and default strategy for positioning `absolute` makes the positioning shifted to be centered around the trigger element. To make it full screen I needed a strategy `fixed`. This works in full scree app, but does not respect parent element. I have no solution for today.

**Comment by jjagielka** [comment]
- [x] Full width dropdown: And in a normal screen, it comes out of the ExampleDiv container.

Corrected by popperjs modifier. No need to `fixed` strategy any more.

**Comment by shinokada** [comment]
A11y problems with navbar page.

https://validator.unl.edu/?showsource=yes&showoutline=yes&doc=https%3A%2F%2Fflowbite-svelte.com%2Fcomponents%2Fnavbar#cl307c338

**Pull request merged**
