### PR TITLE
fix: use negative margin to correct uneven border

### LINKED ISSUE #1360: Incorrect left border or ring width in Button Group
### Describe the bug

The left border or ring width in a button group is smaller than it should be, it's easier to explain with screenshots from the documentation page.

| [Flowbite](https://flowbite.com/docs/components/button-group/#default-example) | [Flowbite Svelte](https://flowbite-svelte.com/docs/components/button-group#Default) |
|---|---|
| Screenshot 2024-06-10 at 09 51 27 | Screenshot 2024-06-10 at 09 52 38 |

If you notice closely, the left border or ring width is smaller than the right. It's easier to tell in the example below.

| [Flowbite](https://flowbite.com/docs/components/forms/#input-element-with-addon) | [Flowbite Svelte](https://flowbite-svelte.com/docs/components/forms#Input_element_with_addon) |
|---|---|
| Screenshot 2024-06-10 at 09 58 44 | Screenshot 2024-06-10 at 09 59 09 |

> [!NOTE]
> Clicking on the header will take you to the the example these screenshots were taken from.

### Reproduction

https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/docs/components/forms.md#input-element-with-addon

### Flowbite version and System Info

```shell
-
```

### PR DESCRIPTION
**Pull request by therealsujitk**
Closes #1360

## 📑 Description

- Sets a margin of `-1px` to all the children of a button group except the first.
- Changed the default`<Button />` color to `light` when inside a `<ButtonGroup />`.
- Corrects the `<ChevronDownOutline />` icon color in the [Forms --> Input Field --> Dropdown](https://flowbite-svelte.com/docs/forms/input-field#Dropdown) example.

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information

_None_

## Summary by CodeRabbit

- **New Features**
  - Updated button and input field styles for improved visual consistency.
  - Enhanced button group styling with new class attributes for better customization.

- **Bug Fixes**
  - Fixed border and color assignment issues for buttons in groups.
  - Corrected input field padding and border logic based on slot presence.

- **Documentation**
  - Updated examples and styling references in button group and input field documentation.

### CODE REVIEW

**Comment by therealsujitk** [comment]
@shinokada the only difference is that the default example in the original flowbite for button group has a primary coloured ring. For now I guess we can ignore this? I'm not really sure why it's like that.

**Comment by shinokada** [comment]
PR:
image
Flowbite:
image

They are still different though.

**Comment by therealsujitk** [comment]
What this PR mainly does is ensures the border and ring appear symmetric (even for the first and last children) which wasn't the case before.

> It doesn't have a primary color.

Yes, this is something I noticed too, but I'm not sure what to do about it. I feel the styling in flowbite is incorrect.
- It has the button style of `light` in dark mode, `alternative` in light mode.
- It has a primary ring instead of the one that the button has, I thought we could set the color to primary for any child of a button group, but then I saw the button [in this example](https://flowbite.com/docs/forms/input-field/#dropdown-input) doesn't have a primary ring.

So I'm not sure what color the ring is supposed to be.

> I think [flowbite.com border](https://flowbite.com/docs/components/button-group/) is too big and I'm not sure if it is intentional.

I'm not sure if I follow, could you elaborate?

**Comment by therealsujitk** [comment]
@shinokada I can add the class in the examples to keep it consistent with the original. I think we shouldn't add this class to the `<ButtonGroup />` component because that'll affect coloured buttons as well.

Screenshot 2024-06-18 at 11 55 22

<hr>

> It has the button style of light in dark mode, alternative in light mode. What button color should we use by default?

For some reason the original tailwind has this mixed styling, which one should we use? It was `alternative` and I changed it to `light`. Should I change it back?

**Comment by shinokada** [comment]
Yes, I agree with you. Users can add the class as your example.
Yes, please use `light` instead of `alternative`. Thank you.

**Comment by therealsujitk** [comment]
> Yes, I agree with you. Users can add the class as your example.

Sorry just to confirm, you want me to update the examples with this class? After that the only difference will be the button text color in light mode (as shown in the image in my previous comment) because we're using `light` instead of `alternative`.

**Comment by therealsujitk** [comment]
@shinokada done! Let me know if there's anything else.

**Pull request merged**
