### PR TITLE
Floating UI

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description

Re-implementation of `Popper` with `@floating-ui`.

- change in `package.json`
  - removed `@popperjs/core`
  - added `@floating-ui/dom`
- `Popper` component re-written
- Few tweaks to `Tooltip`, `MegaMenu`

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
Can you update introduction and quickstart page as well?

**Comment by shinokada** [comment]
This will be a breaking change, so I will release version 0.40.

**Comment by jjagielka** [comment]
What is a breaking change here? The API does not change for any component.

**Comment by shinokada** [comment]
You have to install a different dependency.

**Comment by go-nagai** [comment]
floating-ui/dom has been introduced with dev: true parameter apparently which is KO for me when compiled to production. I need to add it to my package.json as non-dev dependency... using v0.47.4 flowbite-svelte + sveltekit 2.17.3. Production on Firebase hosting with web experimentals. Producing 500 error on prod.

**Comment by jjagielka** [comment]
From `package.json`:
```json
  "dependencies": {
    "@floating-ui/dom": "^1.6.13",
    "apexcharts": "^3.54.1",
    "flowbite": "^3.1.2",
    "tailwind-merge": "^3.0.1"
  },
```

**Pull request merged**
