### PR TITLE
fix: add $$resProps to Spinner

### PR DESCRIPTION
**Pull request by vonagam**
## 📑 Description

Add `$$resProps` to `Spinner`.

## Status

- [ ] Not Completed
- [X] Completed

## ✅ Checks

- [X] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [X] All the tests have passed
- [X] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by jjagielka** [comment]
I'm OK with this PR

**Comment by vonagam** [comment]
Hah, just noticed a type in my commit message `resProps` instead of `restProps`...

**Comment by shinokada** [comment]
Can you create another PR?

**Comment by vonagam** [comment]
It is only in the commit message, not in the code.

**Comment by shinokada** [comment]
Thanks. Then it's ok.
Thank you for your contribution.

**Pull request merged**
