### PR TITLE
docs: update titles for better SEO keyword targeting

### PR DESCRIPTION
**Pull request by zoltanszogyenyi**
## 📑 Description

This PR helps target better SEO keywords and the effect will be a higher growth and coverage on search engines.

It also introduces a new `breadcrumb_title` variable which is a shorter version of the `<title>` and `<h1>` final result.

- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information

No breaking changes, just changing some titles.

### CODE REVIEW

**Comment by zoltanszogyenyi** [comment]
@shinokada I see that the `package-lock.json` file has been pushed, maybe we should add it to `.gitignore`?

It may not play well with building with Vercel, but that remains to be seen.

**Comment by shinokada** [comment]
Thanks. Can you update spec/test files in tests dir? Since you changed titles, all tests fail.

**Comment by zoltanszogyenyi** [comment]
@shinokada sure, I'm doing that right now

**Comment by shinokada** [comment]
After that, can you run `npm run test` or `pnpm test`?

**Comment by zoltanszogyenyi** [comment]
I've updated all of the test files, but when I'm running `npm run test` I get this error:

Screenshot 2022-09-20 at 14 04 21

Am I missing something? The project works for me locally since I've installed all packages including the `npm run dev` command.

**Comment by shinokada** [comment]
You need node >= 16.
Also you need to run `npx playwright install` to install default browsers. It will install Chrome, FF, and Safari.

**Comment by zoltanszogyenyi** [comment]
@shinokada my Node version currently is v18.9.0 and I also ran the `npx playwright install` command, but when I run `npm run test` it times out for some reason.

Screenshot 2022-09-20 at 14 25 18

Any idea why?

**Comment by shinokada** [comment]
I had the same error before and I'm now sure how I solved it. 

1. Can you use node v16.17.x?
2. Restart the editor or terminal
3. If #2 doesn't work, restart your laptop.

**Comment by zoltanszogyenyi** [comment]
Using Node v16.17.x seems to work! I think it's important to mention this when trying to use the test command in the README.

So I've run `npm run test` and all tests seem to have passed.

Screenshot 2022-09-20 at 14 53 47

**Pull request merged**
