### PR TITLE
feat: social proof

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description

Social proof components.

- [x] need to verify icons
- [x] need to implement to get hits dynamically
- [x] need to update copy writing
- [x] need to pull Stars and Download from Flowbite-Svelte
- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
@zoltanszogyenyi I'm not sure about the copy because it is about Flowbite not about Flowbite-Svelte. Isn't it confusing to users?

**Comment by shinokada** [comment]
@zoltanszogyenyi  We need to update Get Started copy as well.

image

**Comment by shinokada** [comment]
It seems you need the server id and discord bot auth token. 
@zoltanszogyenyi may know about it.

```
const serverId = 'YOUR_SERVER_ID';
const authToken = 'YOUR_BOT_AUTH_TOKEN';

fetch(`https://discord.com/api/guilds/${serverId}`, {
  headers: {
    'Authorization': `Bot ${authToken}`
  }
})
.then(response => response.json())
.then(data => {
  const onlineMembers = data.approximate_presence_count;
  console.log(`Number of members online: ${onlineMembers}`);
})
.catch(error => {
  console.error('Error fetching server information:', error);
});
```

**Comment by jjagielka** [comment]
Yes, that's the way I found. I was thinking that you would prefer to register the bot under Themesberg name and just share a token with me.

**Comment by shinokada** [comment]
I am in the same position as you on the Flowbite Discord channel. @zoltanszogyenyi should have access to a setting for the token.

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka @shinokada,

I pulled the data from Discord myself in a commit.

I think that for Figma we can keep it hardcoded for now - the only viable option is scraping the page.

Cheers,
Zoltan

**Comment by shinokada** [comment]
Fixed merge conflicts.

**Pull request merged**
