### PR TITLE
fix: li classes cascaded from ul

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
`Navbar`: use the `setContext` to push classes for `NavbarLi` from 'NavbarUl`. Eliminates the need to repeat the code when navbar is customized.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
Can you explain why this PR eliminates the need to repeat the code when the navbar is customized?

**Comment by jjagielka** [comment]
Previously you needed to make:
```svelte
...
  <NavUl {hidden}>
    <NavLi activeClass="text-red" nonActiveClass="text-blue" href="/" active={true}>Home</NavLi>
    <NavLi activeClass="text-red" nonActiveClass="text-blue" href="/about">About</NavLi>
    <NavLi activeClass="text-red" nonActiveClass="text-blue" href="/services">Services</NavLi>
    <NavLi activeClass="text-red" nonActiveClass="text-blue" href="/pricing">Pricing</NavLi>
    <NavLi activeClass="text-red" nonActiveClass="text-blue" href="/contact">Contact</NavLi>
  </NavUl>
...
```
now you can do like:
```svelte
...
  <NavUl activeClass="text-red" nonActiveClass="text-blue" {hidden}>
    <NavLi href="/" active={true}>Home</NavLi>
    <NavLi href="/about">About</NavLi>
    <NavLi href="/services">Services</NavLi>
    <NavLi href="/pricing">Pricing</NavLi>
    <NavLi href="/contact">Contact</NavLi>
  </NavUl>
...
```
as using `setContext` `NavUl` will push the classes to `NavLi`s

**Comment by shinokada** [comment]
Published in v0.30.6.
Thank you for your PR.

**Comment by shinokada** [comment]
And also you can add a custom class to an individual `li`, if you want:

```
...
  <NavUl activeClass="text-red" nonActiveClass="text-blue" {hidden}>
    <NavLi href="/" active={true}>Home</NavLi>
    <NavLi href="/about" activeClass="text-blue">About</NavLi>
    <NavLi href="/services">Services</NavLi>
...
  </NavUl>
...

**Pull request merged**
