### PR TITLE
Figma

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
The first draft of the new design.
- High level navigation adjusted but needs rethinking
- Landing page not touched yet
- Components pages - full focus was there so far

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
Let me know when you want me to merge.

**Comment by jjagielka** [comment]
This is probably wider team decision. Please play with it and make your opinion what's the minimal state of changes we are OK to show to the world.

**Comment by shinokada** [comment]
- I like you moved the component pages to the docs dir. Later on, we can create the blocks dir to move https://flowbite-svelte-blocks.vercel.app/.

- Any plan to add the sidebar dropdown menu?
Image from Figma:
image

- When I open the sidebar, I don't see any menu.
image

- Top menu for the width of 870px is not styled. 
image

- @zoltanszogyenyi Soon we need to implement the search function. Which library/plugin do you use for Flowbite.com?

**Review by shinokada — COMMENTED** [review]
- [x] I like you moved the component pages to the docs dir. Later on, we can create the blocks dir to move https://flowbite-svelte-blocks.vercel.app/. We can rename the current `src/routes/blocks` to `src/routes/component-thumbnails`.

- [ ] Any plan to add the sidebar dropdown menu? 
Image from Figma:

image

-  [x] When I open the sidebar, I don't see any menu.

image

- [x] Top menu for the width of 870px is not styled. 

image

- @zoltanszogyenyi Soon we need to implement the search function. Which library/plugin do you use for Flowbite.com?

- @zoltanszogyenyi  For "Toggle table view", are we going to use iFrames? Do you have any suggestions?

image


- @zoltanszogyenyi Can you tell us your idea about "Was this page helpful"? Are you thinking to use a database or any library you know for this function without a database?

image

**Comment by jjagielka** [comment]
Menu issue corrected. As for the sidebar folding, it's yet to come soon.

**Comment by jjagielka** [comment]
@shinokada I have made you a space for the `blocks`.

**Comment by zoltanszogyenyi** [comment]
> * I like you moved the component pages to the docs dir. Later on, we can create the blocks dir to move https://flowbite-svelte-blocks.vercel.app/. We can rename the current `src/routes/blocks` to `src/routes/component-thumbnails`.
> * [ ]  Any plan to add the sidebar dropdown menu?
>   Image from Figma:
> 
> image
> 
> * [x]  When I open the sidebar, I don't see any menu.
> 
> image
> 
> * [x]  Top menu for the width of 870px is not styled.
> 
> image
> 
> * @zoltanszogyenyi Soon we need to implement the search function. Which library/plugin do you use for Flowbite.com?
> * @zoltanszogyenyi  For "Toggle table view", are we going to use iFrames? Do you have any suggestions?
> 
> image
> 
> * @zoltanszogyenyi Can you tell us your idea about "Was this page helpful"? Are you thinking to use a database or any library you know for this function without a database?
> 
> image

- I will reach out to my friends from Algolia Search and see if we can get a free quote from them
- using iframes is the only viable solution if we want to properly show responsive view
- we can use an API interface and automatically but them into a Google Excel file for example, but I think we should separate that feature for the next release and create a release with the basic redesign (we should add the next and previous links though, those are nice)

**Comment by jjagielka** [comment]
> I will reach out to my friends from Algolia Search and see if we can get a free quote from them

[Typesense ](https://typesense.org/) is a free alternative. I've used it in few of my other projects.

**Comment by zoltanszogyenyi** [comment]
@jjagielka we already have a free integration for Flowbite and I believe we'll get it for Svelte too - if not then we can check out Typesense too

**Comment by shinokada** [comment]
@zoltanszogyenyi Thank you for your update. Regarding the GitHub source list, there are differences between Flowbite and Flowbite-Svelte. In terms of presentation, Flowbite-Svelte is component-based whereas Flowbite is example-based. I think users and developers will benefit from quick access to the source. 
If it is not suitable at the top of the page, is it possible to add it before or after the props section? What do you think?

**Comment by shinokada** [comment]
@zoltanszogyenyi Do we have an SVG for the dark mode? I can't find it in Figma.

image

**Comment by shinokada** [comment]
- [ ] Copy button is not working. 

image

- [ ] "Featured in" section on the home page.

image

- [ ] Sections after components on the home page.

image

- [ ] Footer on the home page.

image

- [ ] Padding at the top.

image

- [ ] Backdrop above the sidebar menu

image

**Comment by shinokada** [comment]
We don't need a tooltip on Github, Discord, Youtube etc.

image

**Comment by jjagielka** [comment]
They are on the design.
image

**Comment by jjagielka** [comment]
Recent changes:
* [x]  Copy button is not working.
* [x]  Padding at the top.
* [x]  Backdrop above the sidebar menu
* [x]  Remove the top link to the block
* [x]  Footer has two columns for 375px and it should be one column.
* [x]  Mobile should not have the right menu at the top.
* [x]  npm is hard to see. I think we need a stronger color.

**Comment by shinokada** [comment]
Regarding the tooltip, there is not enough space at the top. Even the tooltip in the design is out of the screen.

**Comment by jjagielka** [comment]
Tooltips are now `placement="bottom"`

**Comment by shinokada** [comment]
Around width 1031 px, the left side of the top hero breaks.

image

**Comment by shinokada** [comment]
The sidebar has the different top padding.

image
image

**Comment by jjagielka** [comment]
Try now, please.

**Comment by shinokada** [comment]
The sidebar still has different top padding.

**Comment by shinokada** [comment]
Are you planning to add UI components in Svelte, Dark mode integration, Works with Tailwind CSS, Quote, Get started, and Design with Figma section on the home page?

**Comment by jjagielka** [comment]
- Sidebar padding corrected again.
- Landing page lower sections - I think we can add that later. I'm focused on finalization of the current layout.

**Comment by shinokada** [comment]
- The link to Getting started is broken.
- We can add content to the Getting started page later as well.

**Comment by zoltanszogyenyi** [comment]
Feature request:

We should be able to add custom order to the sidebar elements:

Screenshot 2023-04-18 at 12 13 38

Here it should be something like:

- Introduction
- Quickstart
- Compile speed (though we should rename this to building tools)
- Contributing
- License
- Changelog (we should add this)

**Comment by zoltanszogyenyi** [comment]
Another pretty big issue I've encountered:

If you hit refresh on any of the docs pages there's an `internal server error` appearing:

https://user-images.githubusercontent.com/8052108/232733240-15d1aed5-7c51-4412-ab6e-881a43f26324.mov

**Comment by jjagielka** [comment]
> If you hit refresh on any of the docs pages there's an `internal server error` appearing:

I can't reproduce that. Was that appearing in the local `pnpm run dev` or on the vercel deployment version?

**Comment by zoltanszogyenyi** [comment]
> > If you hit refresh on any of the docs pages there's an `internal server error` appearing:
> 
> I can't reproduce that. Was that appearing in the local `pnpm run dev` or on the vercel deployment version?

I use `npm run dev` which in turn does `vite dev` and I'm testing it on a local development server.

Not sure what happens on Vercel after deployment.

**Comment by shinokada** [comment]
- [ ] Home page footer needs padding

image


- [ ] version number can be pulled from GitHub/NPM API

image

**Comment by shinokada** [comment]
@zoltanszogyenyi I wonder what the arrow next to the version number is for. Is the version number supposed to be a link somewhere?

image

**Comment by jjagielka** [comment]
* [x] Home page footer needs padding
* [x] version number can be pulled from GitHub/NPM API

I think it's high time to merge. This PR becomes difficult to manage.

Unless you find still something to urgently correct.

**Comment by shinokada** [comment]
I will merge now. 
Thank you for a great work.

**Comment by shinokada** [comment]
image

Items in "Featured in" changes the cursor, but it has no links.

**Comment by jjagielka** [comment]
Yeap, links need to be added. I don't know them.

**Comment by shinokada** [comment]
For now we can remove the links.

**Comment by jjagielka** [comment]
OK. I will remove them. Check what else so I can make a slightly larger commit.

**Comment by shinokada** [comment]
Can we add a link to https://www.npmjs.com/package/flowbite-svelte for the version button?

**Comment by jjagielka** [comment]
Done. Anything else?

**Comment by shinokada** [comment]
I think that's it. I'm merging it.

**Comment by shinokada** [comment]
Can you push your commit?

**Comment by zoltanszogyenyi** [comment]
Hey @shinokada and @jjagielka,

Let’s please wait before merging it until tomorrow so I can double check everything as well.

We can take some time to test out responsive views as well since those usually end up being a problem down the line.

Also — is the homepage ready? We will need a bit of custom copywriting there and I can help with that.

**Comment by jjagielka** [comment]
Sure. No rush. We can wait.

> Also — is the homepage ready? We will need a bit of custom copywriting there and I can help with that.

No, it's not ready yet, but we can create another PR for finishing that. No it's quite painful scrolling up and down throughout that one.

**Comment by zoltanszogyenyi** [comment]
@shinokada @jjagielka please don't add the padding back to the footer anymore - it looks good as it is

Screenshot 2023-04-19 at 11 50 02

**Comment by zoltanszogyenyi** [comment]
> @zoltanszogyenyi How about a footer on the home page?
> 
> image

Fair point. I think we should use two different footers as we can put 4 columns of links instead of 3 and it has a different sizing.

Same for the navbar — we should use a max width on the homepage. But the docs navbar and footers are perfect now.

**Comment by jjagielka** [comment]
I've added the place in the `routes\utils\Footer.svelte` to put optional padding depending whether it's home page or not.

**Comment by zoltanszogyenyi** [comment]
@shinokada @jjagielka 

When coming from the homepage or navbar it looks like the sidebar won't open for the currently activate category.

https://user-images.githubusercontent.com/8052108/233131064-e211e64e-f4fd-496b-919f-da7310287c06.mov

**Comment by jjagielka** [comment]
Yeah! I've noticed that as well and I need to think a bit how to implement it. I'll do that tonight.

**Comment by zoltanszogyenyi** [comment]
Okay - I think we're in a pretty good spot. Here's a list of things I think we should fix before the merge and a list of things that we can address with later PRs:

What to fix before main merge:

- let's make sure the sidebar category opens even when just refreshing
- when copying a component code we should show a tooltip and change the text to copied so the end user knows that the content of the box has been added to the clipboard

Screenshot 2023-04-19 at 19 39 18

- we should show a hamburger menu on the homepage with the default links (quickstart, docs, figma etc) it can be on the right side this time
- make sure that all the listed components on the homepage use the new "orange" colors (I can still see some blue ones, I'm not sure if @robert1508 didn't design them yet or that we just forgot to add them)

What to fix after the merge:

- add Algolia search (this is easier after we already have the new docs in place `cause they have to crawl the page data anyways)
- build the remaining sections on the homepage
- add the "newsletter" section at the end of the docs page
- add previous and next links for each page
- add the "was this helpful?" interaction and save that somewhere for feedback
- we could set up a sponsorship strategy and show sponsors instead of "featured in" and we can use the money to support the open-source development and divide it between contributors
- @shinokada we should host whatever is on the blocks repo on `flowbite-svelte.com/blocks` but use the new layout instead of the old one -> I think that I may help here in the future, but we also may just host them on flowbite.com/blocks/ directly as we will build this feature

These are just some of the things that came to my mind - I still have lots of ideas to make the docs better but this is a pretty good start - good job peeps!

**Comment by shinokada** [comment]
I think the breaking point for the top nav is wrong.

image

**Comment by jjagielka** [comment]
I think that's it, unless you spot something else.

> I can still see some blue ones

Those blue component thumbnails are directly from Figma. In my opinion it's not blocking problem.

**Comment by shinokada** [comment]
@zoltanszogyenyi All the blue component images are from Figma.

image

**Comment by shinokada** [comment]
Version number around 1036px.

image

**Comment by jjagielka** [comment]
Which browser do you use?
I've tested it on Firefox and that did not happen.

**Comment by shinokada** [comment]
I tested with Chrome.
fs

**Comment by shinokada** [comment]
As far as I can see, it is ready to be merged.

**Comment by zoltanszogyenyi** [comment]
@shinokada allow me to update the images and review things one last time -- I think we can later merge todat and then work on the other stuff in separate PRs.

**Comment by jjagielka** [comment]
Can you please check as well the content of Introduction and Quickstart? Seems like much duplication of text for me.

**Comment by jjagielka** [comment]
@zoltanszogyenyi and we still need a thumbnail for dark mode component. Just a reminder.

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka,

That's not a problem - the user wants to know how to install Flowbite Svelte by going to the introduction page as well.

This is how we've been having it for Flowbite and the introduction page is one of the most visited pages because it includes both the description of the library AND the quickstart guide.

**Comment by zoltanszogyenyi** [comment]
> 

I think that the current one is quite alright - using a moon/sun icon is good enough.

**Comment by zoltanszogyenyi** [comment]
I think that we're almost ready to merge.

One more thing I would take care of - when you open the navigation menu on mobile devices and go to another page the menu stays open and I believe we should close it as a default behaviour.


https://user-images.githubusercontent.com/8052108/233321818-8d5cfe8d-f4f3-4984-a864-71a530bc449d.mov

**Review by zoltanszogyenyi — APPROVED** [review]
We can merge it!

The other tasks can be broken up into multiple issues and PRs.

@shinokada you do the honors.

Good job peeps! @jjagielka

**Comment by jjagielka** [comment]
Wait a minute.

**Comment by jjagielka** [comment]
> when you open the navigation menu on mobile devices  ...

Done.

**Comment by zoltanszogyenyi** [comment]
Awesome! We're ready to merge @shinokada.

**Comment by shinokada** [comment]
Give me 10 min.

**Review by shinokada — APPROVED** [review]

**Comment by shinokada** [comment]
Merged.
Thank you all. Great work!

**Pull request merged**
