### PR TITLE
fix: correct border and background colors for textarea component

### LINKED ISSUE #1362: Textarea component has an incorrect border color
One more thing, the `<Textarea />` border color is lighter than it should be, or at least it isn't the same as the `<Input />` border. I'll try and see if I can pinpoint the issues for all of these over the weekend.

_Originally posted by @therealsujitk in https://github.com/themesberg/flowbite-svelte/issues/1360#issuecomment-2168362825_

### PR DESCRIPTION
**Pull request by therealsujitk**
Closes #1362 

## 📑 Description

- Corrects the border color of the `<Textarea />` component to match the one from [the official site](https://flowbite.com/docs/components/forms/#textarea).
- Corrects the background color of the `<Textarea />` component when used within a `<Card />` component.
- Adds disabled classes to the `<Textarea />` component for when the `disabled` prop is set to true.

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information

_None_

## Summary by CodeRabbit

- **New Features**
  - Enhanced `Textarea` component styling for better visual consistency across different scenarios.
  - Improved `Textarea` component to handle disabled states with appropriate cursor and opacity changes.
  - Updated documentation for `Textarea` component in chatroom context, improving layout and styling consistency.

- **Bug Fixes**
  - Fixed `Textarea` header class to correctly apply conditional dark mode border styles.

### CODE REVIEW

**Comment by therealsujitk** [comment]
@shinokada I think even disabled styles are missing for `<Textarea />`. Should I add that to a separate PR or push it to this one?

**Comment by shinokada** [comment]
You can add to this PR.
Thanks.

**Comment by shinokada** [comment]
Comparing to the original [Flowbite](https://flowbite.com/docs/forms/textarea/) your color is not correct.

**Comment by therealsujitk** [comment]
I added the `disabled` classes, not sure if I've added them in the right place.

> Comparing to the original [Flowbite](https://flowbite.com/docs/forms/textarea/) your color is not correct.

@shinokada which one are you referring to? It matches with the first example. `border-gray-300 dark:border-gray-500 bg-gray-50 dark:bg-gray-600`

**Comment by therealsujitk** [comment]
@shinokada I've corrected the border color for when the `<Textarea />` component is wrapped, but there is still one issue (which is also there with the `main` version). The [Chatroom Input](https://flowbite-svelte.com/docs/forms/textarea#Chatroom_input) example is inconsistent with the original one. One thing I can do is add the classes in the example itself so it looks the same, what do you think?

**Comment by shinokada** [comment]
Yes, please fix the chatroom input as well.

image

**Comment by shinokada** [comment]
I will release a new version once this PR is merged. Thanks.

**Pull request merged**
