### PR TITLE
feat: radio, checkbutton, toggle

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
Forms buttons Radio, Checkbox and Toggle re-written with shared code.
- All use input embedded in label removing the need of separate id setting
- Simplified API
- Passes all allowed `input` attributes to underlying `input`: id, name, value, disabled, checked, etc.
- Use `Helper` component to add extra info for elements

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit/version

## ℹ Additional Information
This a replacement of the #152 PR.

### CODE REVIEW

**Comment by shinokada** [comment]
I'd like to merge the PR, but I'm having a difficulties since you pull new commits with different commit hash.

I think, if you can run `git pull --rebase`, it could be easier.

**Comment by jjagielka** [comment]
I have an issue with rebasing. 

This PR is touching only those 5 files:
        modified:   src/lib/forms/Checkbox.svelte
        modified:   src/lib/forms/Radio.svelte
        modified:   src/lib/forms/Toggle.svelte
        modified:   src/routes/forms/radio.md
        modified:   src/routes/props/Radio.json

Can you update those manually?
The other option is I close that PR. Make complete rebase and create new PR.

**Comment by shinokada** [comment]
Don't you mind if I just copy/paste those 5 files?
Your commits won't reflect on the commit log.

**Comment by jjagielka** [comment]
Replaced with #162

**Pull request closed without merging**
