### PR TITLE
feat: add use:action to SidebarItem

### LINKED ISSUE #933: SidebarItem not usable with use:action
## Summary

Its relatively common to use `use:action` directives on `<a>` in svelte, but SidebarItem doesn't support that yet.
So it would be good to either have a new `action` prop which passes a directive to the anchor inside, or add a slot to be able to overwrite the anchor inside of it.

### Basic example

```svelte
<script>
  // using https://inertiajs.com/pages#creating-layouts 
  import { inertia } from '@inertiajs/svelte'
</script>

// ...
{#each routes as { name, href }}
  <SidebarItem {href} label={name} action={inertia} />
{/each}
// ...
```

```svelte
<script>
  // using https://inertiajs.com/pages#creating-layouts 
  import { inertia } from '@inertiajs/svelte'
</script>

// ...
{#each routes as { name, href }}
  <SidebarItem>
    <a {href} use:inertia>{name}</a>
  </SidebarItem>
{/each}
// ...
```

### Motivation

Im currently building an app with a Laravel backend where i use Inertia to get the user experience of an SPA.
Inertia (like other libraries) performs the routing in the frontend via directive on anchors and im not able to do that with the SidebarItem since `use:action` directives only work on DOM-Elements.

### PR DESCRIPTION
**Pull request by shinokada**
Closes #933

## 📑 Description

- add `use:action` to the `a` tag
- add example to docs/components/sidebar

## Status

- [x] Not Completed
- [ ] Completed

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
@jjagielka Can you have a look at this PR? What do you think?

**Comment by jjagielka** [comment]
1. Your implementation of the action misses the parameters. Please take a look at `Frame` component where actions are implemented by 2 props: `action` and `options`. 
2. Why `Sidebar`'s `a` element is so special that requires the `action`? Why not to add it on all components?

**Comment by shinokada** [comment]
@jjagielka Thanks.
That's what I asked about your Q2. https://github.com/themesberg/flowbite-svelte/issues/933#issuecomment-1712569492

**Comment by kripi-png** [comment]
Any progress on this? I would like to have use:action available for other elements as well.
For example, on Input elements, it would allow dynamic types via a helper component.

**Comment by shinokada** [comment]
I close the PR for now.

**Pull request closed without merging**
