### PR TITLE
fix: Clicking on dropzone component triggers onsubmit event on parent…

### PR DESCRIPTION
**Pull request by anjaneyasivan**
Closes #

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information

-----
<a href="https://stackblitz.com/~/github/anjaneyasivan/flowbite-svelte/tree/anjaneyasivan%2Fissue906">Review PR in StackBlitz Codeflow</a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github/anjaneyasivan/flowbite-svelte/tree/anjaneyasivan%2Fissue906)._

### CODE REVIEW

**Comment by shinokada** [comment]
Thank you for your PR.
Since the tag is `button`, you don't need to add `type="button"`.

I close this PR but I'm looking forward to seeing your future PRs.
Thank you for your contribution.

**Comment by anjaneyasivan** [comment]
@shinokada, thanks for clarifying. I happened to notice that the `Dropzone.svelte` file contains an `input` tag inside a `button`  tag. I was just wondering if this is considered semantically correct.  Thank you for your time and help!

**Comment by fuzzie360** [comment]
Hi @shinokada, I'm affected by the issue referenced here https://github.com/themesberg/flowbite-svelte/issues/906 and this fixes my issue exactly.

I don't understand the reason behind the closure:

> Since the tag is button, you don't need to add type="button"

The default attribute for the button tag for many browsers is `"submit"` not `"button"`. This will cause the `Dropzone` to trigger a form submit if it is in a `form`.

Perhaps `Dropzone` should be more props so that we can control wether `Dropzone` will submit or not submit  depending on the use case.

Wdyt?

**Comment by shinokada** [comment]
I reopened this and will merge it.
It will be in the next version.
Thank you for your PR.

**Pull request merged**
