### PR TITLE
fix: input number workaround

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
Proposal of the workaround for dynamic `input` type.

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
1. Do you need `$$slots.default`? 

```
{#if $$slots.default}
    <slot props={{ ...$$restProps, class: inputClass }} />
  {:else}
```

There is no examples using that named slot.

2. Have all the test passed?

**Comment by jjagielka** [comment]
1. https://flowbite-svelte-update-op8pewvkw-themesberg.vercel.app/forms/input-field#Advanced_usage
2. yes, tests passed. Sorry for not checking out the checkboxes.

**Comment by shinokada** [comment]
Instead of this:

```
{#if $$slots.default}
  <slot props={{ ...$$restProps, class: inputClass }} />
{:else}
```

Can we use this?

```
<slot props={{ ...$$restProps, class: inputClass }} />
```

**Comment by jjagielka** [comment]
You're right. Corrected.

**Comment by shinokada** [comment]
And did you pass the tests?

**Comment by jjagielka** [comment]
Yes. All pass.

**Pull request merged**
