### PR TITLE
EXPERIMENTAL: Layout components

### PR DESCRIPTION
**Pull request by shinokada**
Relating this issue: https://github.com/themesberg/flowbite-svelte/issues/542

## 📑 Description

- LayoutWrapper, LayoutHeader, LayoutFooter, PageContent, PageFooter, PageHeader, SidebarLeft, SidebarRight
- extend/layout page

## Status

- [x] Not Completed
- [ ] Completed

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
@jjagielka Can you have a look at this experimental components?

**Comment by jjagielka** [comment]
To be honest, I don't get the value of that. What does it bring? What problem does it solve?

We have already `Footer`, `Navbar`, `Sidebar` elements. Why do we need a layout to use them?

**Comment by shinokada** [comment]
Users can add Navbar and other divs in the LayoutHeader and the Footer components and other divs in the LayoutFooter component. And it just makes it easier for users to scaffold the layout.

**Comment by jjagielka** [comment]
They can equally put Footer in LayoutHeader and Navbar in LayoutFooter.

Anyway, for me it sound like a redundancy. If it's recommended to put Footer in LayoutFooter, why not to make it as on component?

**Comment by shinokada** [comment]
Yes, I agree with LayoutFooter. I just replaced it with the Footer component.
Yes, I agree with Navbar, but the name Navbar is misleading to me. 

Renaming Navbar to a more generic name, like Header sounds good to me.

**Comment by jjagielka** [comment]
As stated previously I'm not convinced to that. I don't see the value in it. 

For me layout is not a component. It should be in the different section like page setup.

**Comment by shinokada** [comment]
That's why I added the page under the extend section. 
I think these components make it easier for users to scaffold the layout.
This is just a help page and it is up to users what they put in these components.
They are just helpers as we have other components like Step Indicator and Marquee Banner.

**Comment by zoltanszogyenyi** [comment]
@shinokada

We shouldn't rename navbar to header because people search for it more often on Google - in fact a very visited page is "Svelte Navbar" based on a keyboard from Google search analytics.

We should definitely NOT change any of the following existing components: `Navbar`, `Footer`, `Sidebar`.

If you want to add a new one called `Layout` that's fine I guess, though as @jjagielka stated I'm also not convinced it should be a component in itself - with the main library we don't feel that we need such a thing as users would usually use the classes from Tailwind CSS to set them up.

Cheers,
Zoltan

**Comment by shinokada** [comment]
Ok, thank you for your input.
I will close this PR.

**Pull request closed without merging**
