### PR TITLE
feat: more alert options

### PR DESCRIPTION
**Pull request by edde746**

### CODE REVIEW

**Comment by shinokada** [comment]
Thanks for the PR. I will have a look.

**Comment by shinokada** [comment]
- [ ] [Additional content](https://flowbite-svelte-git-fork-edde746-main-themesberg.vercel.app/alerts#Additional_content) dismiss is removed. Can you add it?

- [ ] Since all paragraph in the dark mode is black, I will put it back the CSS.
image

- [ ] Thank you for refactoring all the CSS. 
- [ ] Test fails.
image

**Comment by edde746** [comment]
Fixed all the issues mentioned.

**Comment by shinokada** [comment]
Thanks. I merged it. 
- Due to A11y I put back CSS and added more CSS.
- I changed dismiss to Go to Home.

**Pull request merged**
