### PR TITLE
feat: mdsvexample second try

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
`mdsvexample` - another try to make a PR

- no need to duplicate code and example
- import can now be `flowbite-svelte`
- `mdsvexample` workaround with `class` not needed anymore
- `alert.md` shows the advantage of that PR

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

If your branch is behind the upstream main, I may have difficulties to merge the request. Please fetch the latest version of the main branch:

### CODE REVIEW

**Comment by shinokada** [comment]
I wait this until I fix the website. After merging the previous two PRs, localhost, build/preview, test works but the website is down. I contacted Vercel 12 hrs ago.

**Comment by shinokada** [comment]
Does @popperjs/core need @floating-ui/dom?
It works without it locally and pass all the test etc. But it doesn't work for a live website on Vercel.

**Comment by shinokada** [comment]
Can you rebase the current branch? The main branch has changed and it doesn't have some commits as your PR. 
I'm sorry for the trouble. 
BTW, the website is online. The cause was @floating-ui/dom that I uninstalled. I don't know why we need it though.

**Comment by jjagielka** [comment]
Updated. Can you please check now?
If all good, I can switch to work on dropdowns.

**Comment by shinokada** [comment]
I get this error message:

```
failed to load config from /Users/shinichiokada/Svelte/FLOWBITE-SVELTE/flowbite-svelte/vite.config.js
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'mdsvexamples' imported from /Users/shinichiokada/Svelte/FLOWBITE-SVELTE/flowbite-svelte/vite.config.js.timestamp-1663317149754.mjs
...
```

Do I need to install anything?

**Comment by jjagielka** [comment]
Yes. It's in the `package.json`:
- `"mdsvexamples": "^0.3.2",`

**Comment by shinokada** [comment]
Merged. I also installed @floating-ui/dom since it was the main cause of Vercel website down.
...
Mmmmm...

And I just found the website is down.
I will revert it.

**Comment by shinokada** [comment]
This link is your deployment, https://flowbite-svelte-4wb9lkyme-themesberg.vercel.app/
It has the same issue when the site was down.
I installed @floating-ui/dom and worked last time.
I did the same thing and it didn't work this time.
I will investigate and let you know.

**Comment by shinokada** [comment]
The problem is that it build without errors and I can't find it why.

**Comment by jjagielka** [comment]
Hmm. I don't know how to help. All works OK on my local installation.

If any hint, it seems that things go wrong each time `package.json` changes the dependency list: add or remove the packages.

**Comment by jjagielka** [comment]
When I try to see the vercel preview I'm receiving the error `Invalid request body`

Quick search brought me to: https://github.com/sveltejs/kit/issues/3519 , but I'm not sure it's related.

**Comment by shinokada** [comment]
I know it works local, build/preview but vercel.

**Comment by shinokada** [comment]
I made a branch from main and I copy/pasted file by file from your PR. But it doesn't work either.
https://flowbite-svelte-r8em6u5rm-themesberg.vercel.app/

**Comment by shinokada** [comment]
I think it is something to do with pnpm-lock file. After uninstalling and installing @floating-ui/dom the website breaks. I don't know why.

**Comment by jjagielka** [comment]
In my previous `mdsvexample` PR the failure was with `pnpm-lock.yaml` as well.
It helped to use `pnpm install --no-frozen-lockfile`

**Comment by shinokada** [comment]
Ok, I think I fixed it.
Can you sync your fork and start from there?

**Comment by jjagielka** [comment]
Can you install `mdsvexamples@v.0.3.2` as devDependancy? Then I avoid to mess with `pnpm-lock.yaml`.

**Comment by shinokada** [comment]
Sure I will.

**Comment by jjagielka** [comment]
Did a new branch, installed `msdvexamples` with `pnpm install -D --save msdvexamples` and got failures.

**Comment by shinokada** [comment]
`pnpm i -D mdsvexamples`

**Pull request merged**
