### PR TITLE
feat: newsletter form

### LINKED ISSUE #667: Add newsletter section at the end of each doc page
## Summary

- [ ] Add newsletter section at the end of each doc page

Screenshot 2023-04-20 at 13 43 56

Source in Figma: https://www.figma.com/file/dPNSc2GnxMbP2zmGbB4iKI/Flowbite?node-id=1%3A231693&t=UO2nxuSeEw5W1x2i-1

### PR DESCRIPTION
**Pull request by jjagielka**
- [ ] Not completed
- [x] Completed

Closes #667 
## 📑 Description
Newsletter section.

TODO: subscription command
- send by 'on:click'
- or send as a form action?
- what is the address the e-mail should be sent to?

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by jjagielka** [comment]
@zoltanszogyenyi where should the user's email be sent to?
I found that: `action="https://app.convertkit.com/forms/4692392/subscriptions"` in Flowbite.com. Should I copy paste the data from there or `flowbite-svelte` would have another parameters?

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka,

Yeah that should be okay - I'll test it out later if it gets added to our ConvertKit account.

I think we'll need to add a tag for `svelte` at some point so we can better target them.

**Comment by shinokada** [comment]
FYI: error messages

image

**Comment by shinokada** [comment]
Now it is working. Is this PR completed?

image

**Comment by jjagielka** [comment]
Yes, it is.

**Pull request merged**
