### PR TITLE
update toast styles to fit latest official styles

### PR DESCRIPTION
**Pull request by RyanZhiNie**
## 📑 Description

Update the styles of the toast component to fit [the latest official styles ](https://flowbite.com/docs/components/toast/)

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
@jjagielka Are you happy with this PR?

**Comment by jjagielka** [comment]
Not at all. This PR introduce the new colors: `info`, `danger` and disables normal color management i.e. 'primary', 'red', 'blue', ...
More over those new colors are now called `level`s. 

However, I must admit that something went wrong with `Toast` component and currently it doesn't look in accordance with Flowbite.com.

**Comment by RyanZhiNie** [comment]
My understanding of Colors of the Toast component in Flowbite is not just for colors but for practical meaning, they are used to make the toasts somewhat like alerts.

image

That's the reason why I remove the `color` prop and introduce the more practical `level` prop. However, users can still use their desired colors by set the `level` prop `none` and use explicit tailwind classes.

What's more, the `primary`, `red`, `blue` ... are difficult to define FOR THE TOAST COMPONENT because there are NOT defined by Flowbite.com. For me, I'd rather leave it to users to decide.

**Comment by shinokada** [comment]
@RyanZhiNie Thank you for your PR and contribution.

The following is the comparison of two versions.

## Current Version:

- Simplicity: Fewer props and a simpler structure for easier understanding and use by developers unfamiliar with complex configurations.

## PR Version:

-  Level Colors: Additional styling options like color levels and customizable classes for versatile design adaptation. Different color levels convey message types or importance levels through visual cues.

**Comment by RyanZhiNie** [comment]
I have updated this PR to reintroduce the `color` prop. Users can now easily change the colors either by setting the `level` prop for practical usage or setting the `color` prop just for changing colors : )

**Comment by jjagielka** [comment]
I still don't get why to introduce `level`. What's the difference between `color="red"` and `level="danger"`? They both produce identical code. Why not to stay with color only? Because we lack the `orange` color? We can add it.

**Comment by RyanZhiNie** [comment]
Remove the `level` prop.

**Comment by shinokada** [comment]
[colorPalette](https://github.com/themesberg/flowbite-svelte/pull/763/files#diff-9c0c6d373106c8997819a83c7db2242991dc1ed1df2d2aa0a4806e310cd26b79R48) should have none with ''.

**Comment by RyanZhiNie** [comment]
> [colorPalette](https://github.com/themesberg/flowbite-svelte/pull/763/files#diff-9c0c6d373106c8997819a83c7db2242991dc1ed1df2d2aa0a4806e310cd26b79R48) should have none with ''.

Done.

**Comment by jjagielka** [comment]
I have just two comments left for that PR:
- color gray needs `dark:bg-gray-700` otherwise it's the same as background
- `extraIconClass` is an excess, please leave just `defaultIconClass`, we should no make the API grow too much

**Pull request merged**
