### PR TITLE
run playwright on ci

### PR DESCRIPTION
**Pull request by christophsturm**
this pr runs playwright on github ci.

it could also run lint and sveltekit check, but those currently report failures.

### CODE REVIEW

**Comment by shinokada** [comment]
Error on Run Playwright test.

image

**Comment by shinokada** [comment]
Error.

image

**Comment by christophsturm** [comment]
yes, I don't know why it fails, it works locally and on other projects where I use that workflow.

**Comment by shinokada** [comment]
Can you resolve the conflicting files?
Some of the packages are new but some are old.

**Comment by shinokada** [comment]
@christophsturm Can you check what's wrong with this, please?
All the tests pass locally, but when I create a PR, it fails.
Is it because of the new package versions?

**Comment by shinokada** [comment]
@christophsturm Don't worry. I think I know how to fix it.

**Comment by christophsturm** [comment]
Just need to bump the docker image version in the workflow

**Comment by shinokada** [comment]
@christophsturm I fail the [workflow](https://github.com/themesberg/flowbite-svelte/actions/runs/4547726681/jobs/8018651733) with this error message.

```
[WebServer] Could not resolve "../props/CardPlaceHolder.json" from "src/routes/components/skeleton.md"
file: /__w/flowbite-svelte/flowbite-svelte/src/routes/components/skeleton.md
```

The test passes locally but not with CI.
What could be the causes?

**Comment by shinokada** [comment]
@christophsturm I'm getting errors and not able to solve it. Can you have a look at it?

https://github.com/themesberg/flowbite-svelte/actions

image

**Comment by shinokada** [comment]
@christophsturm Never mind. It started working again on GitHub. It is very strange. Thanks anyway.

**Pull request merged**
