### PR TITLE
fix redirections'

### LINKED ISSUE #671: Redirect old pages to new URLs
### Describe the bug

In order to prevent a huge SEO penalization we need to `301` redirect all previous URL formats.

For example, Google indexed the navbar as such:

https://flowbite-svelte.com/components/navbar

This now returns a 404 error which is super super bad. We need to 301 redirect it to:

https://flowbite-svelte.com/docs/components/navbar

This is a HUGE priority and should be fixed in matters of minutes and hours.

### Reproduction

Just go to the URL.

### Flowbite version and System Info

```shell
Doesn't matter.
```

### PR DESCRIPTION
**Pull request by jjagielka**
Closes #671

## 📑 Description
Quick and dirty workaround for the redirections issue.

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by zoltanszogyenyi** [comment]
@jjagielka you beat me to it :)

Screenshot 2023-04-20 at 14 22 05

**Comment by shinokada** [comment]
Redirections are working. Can I merge it?

**Comment by zoltanszogyenyi** [comment]
Yes @shinokada - we're good to go.

**Comment by shinokada** [comment]
Merged!

**Comment by shinokada** [comment]
@zoltanszogyenyi Due to the time zone difference, if I'm not online and it is urgent, go ahead to press "Squash and merge".

**Pull request merged**
