### PR TITLE
fix: scrolling in modal

### LINKED ISSUE #633: Modal - can't scroll inside text area
### Describe the bug

When using `<Textarea>` component inside of `<Modal>`, I can't scroll inside the `<Textarea>`, even when it shows the scroll bar. I think I found the problem (as much as I tested), but I don't know how to fix it. I also found that when modal has scroll bar, I can scroll inside text area without any problems.

> Note: All the following steps, that happen inside browser, were done inside Edge

Some kind of a fix, that I found inside browser inspector:
1. Right click on text area -> Inspect
2. When `<textarea>` is selected in `Elements` window, press on `Event Listeners`
3. Find `wheel`
4. Inside `wheel`, find element `div#modal.p-6.space-y-6.flex-1.overflow-y-auto.overscroll-contain`
5. Press `Toggle Passive`

After doing these steps, it allows scrolling inside the `<textarea>`, but then there is an error in the console: 
```
Unable to preventDefault inside passive event listener invocation.
preventWheelDefault @ VM58:4206
eval @ VM58:222
```

I also found, that this error might be here: `Modal.svelte` -> `function preventWheelDefault(e)` -> line 80, mainly `e.preventDefault()`.

I guess `isScrollable` function wrongly calculates, because it doesn't take `textarea` size into account, but I might be very wrong.

### Reproduction

https://svelte.dev/repl/ba6de962057f49f2bf32f0e833825ca7?version=3.57.0

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz    
    Memory: 15.75 GB / 31.92 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 111.0.5563.111
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/kit: ^1.14.0 => 1.14.0
    flowbite-svelte: ^0.34.2 => 0.34.2
    svelte: ^3.57.0 => 3.57.0
    vite: ^4.2.1 => 4.2.1
```

### PR DESCRIPTION
**Pull request by jjagielka**
Closes #633 

## 📑 Description
Allows scrolling form elements inside the modal.

Removes `preventDefault` from the `on:wheel` handler. I not sure about the side effects as I have limited ability to test it on different browsers. 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
@aidvai-sp Is it possible to test this?

**Comment by aidvai-sp** [comment]
Yes, one moment

**Comment by aidvai-sp** [comment]
I can't seem to find a way to `npm install` the package from github. I do `npm install https://github.com/jjagielka/flowbite-svelte.git#0afc10ee345ad11a7959912f8930905b63d92dc0` and npm clones the package from github, but the package seems to be empty, it contains only `LICENSE`, `package.json` and `README.md` files. Maybe you could help on how I should properly install it to test it?

**Comment by shinokada** [comment]
@aidvai-sp The easiest way is that you modify the node_modules/flowbite-svelte/src/lib/modals/Modal.svelte file.

**Comment by aidvai-sp** [comment]
Tried that, it seems that all is working well now. Tried it on edge and chrome

**Comment by aidvai-sp** [comment]
But when I open the modal, I get this warning: `index.mjs:425 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

**Comment by shinokada** [comment]
@aidvai-sp jjagielka added another commit. Can you try it again and let us know? Thanks.

**Comment by aidvai-sp** [comment]
I couldn't find the other commit, so I can't check it. Can you link it to me?

**Comment by shinokada** [comment]
@aidvai-sp Can you check it and let us know.

**Comment by aidvai-sp** [comment]
Adding `passive` still shows those message

**Comment by umesh-timalsina** [comment]
Folks, any movement on this PR?

**Pull request closed without merging**
