### PR TITLE
Modal

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
Modal component re-written. 
- New API
- Only one file: Modal.svelte
- Docs rewritten to be in sync with Flowbite.com

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information
Modal sizes are not consistent in the Flowbite.com
In the example section `Sizes` it defines:
- small modal - `max-w-md`
- default modal - `max-w-lg`
- large modal - `max-w-4xl`
- extra large modal - `max-w-7xl`

However in the very first example `Default modal` they use the value of `max-w-2xl`.

I have implemented my approach to sizing. Please verify.

### CODE REVIEW

**Comment by shinokada** [comment]
Thank you for your work. Merged.

**Comment by shinokada** [comment]
In a small screen, bottom-left etc, placement are not working.

Bottom-left
image

**Comment by maku** [comment]
@jjagielka  It would be fine when a focus trap is implemented in modal

**Comment by shinokada** [comment]
@maku @jjagielka updated the modal, https://github.com/themesberg/flowbite-svelte/pull/191, please check it and let us know.

**Comment by maku** [comment]
@shinokada @jjagielka yeah I would say it works perferct. Thank you 👍

**Comment by shinokada** [comment]
For components that uses human interaction, such as modal, alert, etc. can benefit using the dialog element for the future version.
It has the `open` attribute as well.

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#result
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

**Pull request merged**
