### PR TITLE
feat: button group

### PR DESCRIPTION
**Pull request by jjagielka**
## 📑 Description
Button group without the `ButtonGroupItem` component. Use standard `Button` to achieve grouping layout.
- deleted `ButtonGroupItem`
- grouping layout classes in `Button`
- inconsistency of Flowbite.com button rendering `Alternative` and `Dark`. Those color buttons change colors depending on context unfortunately.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information
I've added some extra examples in the button group documentation. Mainly for testing purpose. Those can be removed if not needed.

### CODE REVIEW

**Comment by shinokada** [comment]
Well come back Jakub!

When I hover a link my cursor doesn't change to a pointer.

image

**Comment by jjagielka** [comment]
It does for me. Can you please share the DOM it is rendered to?

**Comment by shinokada** [comment]
It doesn't show on this gif but I get a vertical line when I hover the example.
button-group

I get a pointer cursor on other button-group.
button-group2


I get from you deployment, https://flowbite-svelte-b983stl8q-themesberg.vercel.app/button-groups.

**Comment by jjagielka** [comment]
OK. I can reproduce. Let me take a close look at that.

**Comment by shinokada** [comment]
Thanks. 
I checked it with Chrome, FF, Safari, and Brave and all have the same.

**Comment by jjagielka** [comment]
Found that. Corrected.

**Comment by shinokada** [comment]
Merged.
Next git push will show the merged commit notice.

**Pull request merged**
