### PR TITLE
fix: add modalId prop for Modal

### LINKED ISSUE #771: Modal id is fixed
### Describe the bug

Modal.svelte has the id variable fixed.

```
  <!-- Modal body -->
        <div
          id="modal"
...
```

### Reproduction

N/A

### Flowbite version and System Info

```shell
N/A
```

### PR DESCRIPTION
**Pull request by RyanZhiNie**
Closes #771

## 📑 Description

Add the `modalId` prop to set the id attribute for the generated modal element.

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
It looks good to me.
@jjagielka What do you think?

**Comment by shinokada** [comment]
Thank you for the PR.
I modified a bit.

- use id instead of modalId
- add `outsideclose` prop to close a modal by clicking the outside modal
- dependencies updates
- workflow update
- etc.

**Comment by jjagielka** [comment]
Why did we need that `id` to be set? Original code has already ` <Frame rounded shadow {...$$restProps} class={frameClass}>` and you were able to set `id` via `$$restProps`.

You have now introduce a **static** id called `outsideModalId` which is against the framework creation rules.

**Comment by jjagielka** [comment]
For the outside close it was as easy as adding one line to `onAutoClose` handler and no `id` settings was needed.
```js
const onAutoClose = (e: MouseEvent) => {
    const target: Element = e.target as Element;
    if (autoclose && target?.tagName === 'BUTTON') hide(e); // close on any button click
    if (outsideclose && target === e.currentTarget) hide(e); // close on click outside
  };
```

**Comment by shinokada** [comment]
@jjagielka Thank you for your input. I just updated the Modal component.

**Comment by jjagielka** [comment]
@shinokada I'm sorry I've noticed a small issue with the solution proposed. That handler is conditionally connected:
```svelte
on:click={autoclose ? onAutoClose : null}
```
we need to change it to:
```svelte
on:click={onAutoClose}
```
or
```svelte
on:click={autoclose || outsideclose ? onAutoClose : null}
```

**Comment by shinokada** [comment]
@jjagielka [Done](https://github.com/themesberg/flowbite-svelte/pull/791) and thanks.

**Pull request merged**
