### PR TITLE
fix(Dropdown): default padding should be `py-2`

### PR DESCRIPTION
**Pull request by V-ed**
## 📑 Description

This PR fixes a visual issue with how `Dropdown`s render their hovered items : with the default `py-1`, the hovered item exits the boundary of the rounded corners of the container.

<table>
<tr>
 <td>Before
 <td>After
<tr>
 <td>
 <td>
</table>

Switching from `py-1` to `py-2` aligns with how Flowbite sets by default [in their doc](https://flowbite.com/docs/components/dropdowns/) :
image

## Status

- [x] Not Completed (waiting for feedback [on comment below](https://github.com/themesberg/flowbite-svelte/pull/1088#issuecomment-1734296297))
- [ ] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

## ℹ Additional Information

Currently, the workaround is to manually add `<Dropdown class="py-2" [...]>` to every Dropdown usage. I like the default style, and I'd like to use it easily without having to create my own custom wrapper for a simple class change which should be considered an issue to begin with.

### CODE REVIEW

**Comment by V-ed** [comment]
Looking at the preview website, I think one issue might come from this is that both the `headerClass` and the `footerClass` also define `py-1`, making weird inconsistent paddings :

image

Should these also be switched to this? :
```diff
-export let headerClass: string = 'py-1 overflow-hidden rounded-t-lg';
-export let footerClass: string = 'py-1 overflow-hidden rounded-b-lg';
+export let headerClass: string = 'pt-2 pb-1 overflow-hidden rounded-t-lg';
+export let footerClass: string = 'pt-1 pb-2 overflow-hidden rounded-b-lg';
```
... which would allow to keep the `p-1` margin between elements, but `p-2` for the top/bottom paddings of the container.

**Comment by shinokada** [comment]
Let me know if this PR is completed.

**Comment by V-ed** [comment]
> Looking at the preview website, I think one issue might come from this is that both the `headerClass` and the `footerClass` also define `py-1`, making weird inconsistent paddings :
> 
> image
> 
> Should these also be switched to this? :
> ```diff
> -export let headerClass: string = 'py-1 overflow-hidden rounded-t-lg';
> -export let footerClass: string = 'py-1 overflow-hidden rounded-b-lg';
> +export let headerClass: string = 'pt-2 pb-1 overflow-hidden rounded-t-lg';
> +export let footerClass: string = 'pt-1 pb-2 overflow-hidden rounded-b-lg';
> ```
> ... which would allow to keep the `p-1` margin between elements, but `p-2` for the top/bottom paddings of the container.

This was never answered...

**Comment by shinokada** [comment]
Yes, it is a good idea to add:

```
+export let headerClass: string = 'pt-2 pb-1 overflow-hidden rounded-t-lg';
+export let footerClass: string = 'pt-1 pb-2 overflow-hidden rounded-b-lg';
```

Can you fix the conflicting files to align with the latest?

**Comment by V-ed** [comment]
@shinokada , your merge overwrote mine and the padding is still `py-1`. Because of the merge, this PR now technically only adds a single empty line in the codebase.

**Comment by V-ed** [comment]
Like, not gonna lie this whole PR was not fun at all, [waiting for 5 months for a lackluster review](https://github.com/themesberg/flowbite-svelte/pull/1088#issuecomment-1963020266), [waiting another 2 months for an actual feedback](https://github.com/themesberg/flowbite-svelte/pull/1088#issuecomment-2067168764), then a merge that completely overrides what I did, dismisses the actual review of adding proper padding to the other elements, then (not dramatically) tarnish my committer status as an author of an empty commit in a public repo.

I'm not angry at all, simply disappointed.

Love the design, but I think the structural issues with this library is making me want to switch.

I know this message makes me seems entitled to having free support, but I hope I can make it clear that I don't, I just want to express how I felt with the usage of this library in general.

Anyhow, good luck with the rest!

**Pull request merged**
