### PR TITLE
allows link click event

### PR DESCRIPTION
**Pull request by 524c**
Closes #

## 📑 Description

This PR is to allow links to receive click events.

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by jjagielka** [comment]
Why do we add `on:click` on links. This is discouraged by HTML standards. You should use `button` if you want `on:click` events.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#onclick_events

**Comment by 524c** [comment]
In my interpretation what Mozilla says is: Link allows a malicious actor to use target="_blank" or href to # or javascript:void(0). It does not mean that the `<a>` tag is insecure.

In my case, the PR was because in an ongoing project I have links with click events, so since I'm using other Flowbite components, such as buttons, inputs, etc.. I might as well use `<A>`.
Does the `<a>` vanilla tag support clicks, so to follow the standard `<A>` should also support it, and let the programmer decide what to use in his project? 🤔

**Comment by 524c** [comment]
In my interpretation what Mozilla says is: Link allows a malicious actor to use target="_blank" or href to # or javascript:void(0). It does not mean that the `<a>` tag is insecure. If component `<A>` does not follow the standard, it will not prevent malicious people from using the vanila `<a>` tag to achieve their goals..

In my case, the PR was because in an ongoing project I have links with click events, so since I'm using other Flowbite components, such as buttons, inputs, etc.. I might as well use `<A>`.

Does the vanilla `<a>` tag support clicks, so to follow the standard `<A>` should also support it, and let the programmer decide what to use in his project? 🤔

**Comment by jjagielka** [comment]
I was not pointing to the security concerns but to the paragraph titled `onclick events`:

> Anchor elements are often abused as fake buttons by setting their href to # or javascript:void(0) to prevent the page from refreshing, then listening for their click events .
> These bogus href values cause unexpected behavior when copying/dragging links, opening links in a new tab/window, bookmarking, or when JavaScript is loading, errors, or is disabled. They also convey incorrect semantics to assistive technologies, like screen readers.
> Use a [<button>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) instead. In general, you should only use a hyperlink for navigation to a real URL.

HTML standards says nothing about `click` events on `a` element: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element.

Framework, as that, should promote the standard usage of components and/or elements. Of course it can't prevent the misuse. When the programmer is decided, he can always find a hack to abuse the framework.

**Comment by 524c** [comment]
> Framework, as that, should promote the standard usage of components and/or elements. Of course it can't prevent the misuse. When the programmer is decided, he can always find a hack to abuse the framework.

yes.

**Comment by jjagielka** [comment]
Repeating my question: why do we add the `on:click` on links?
Can we revert that PR?

**Comment by 524c** [comment]
> Repeating my question: why do we add the `on:click` on links? Can we revert that PR?

How about because it's a standard of the current version of HTML? 🤔
How about, there's an entire internet that uses link click events? 🤔

This is an example of a simple PR I did in Sveltekit, which uses a lot of tests with click events:
https://github.com/sveltejs/kit/commit/0a45b71a8fb64804763a4aff963769cfdbe49863

**Comment by jjagielka** [comment]
> How about because it's a standard of the current version of HTML? 

It is not. Read my previous comment. The fact that you can add a `click` event listener on `<a>` does not constitute the standard. Should we also add `on:click` event forwarder to `<HR>` component? Or `<blockquote>`? Svelte allows that ...

And the example you showed is a pure abuse of `<a>` elements. Not only having `onclick` handler, but not even setting the compulsory `href` attribute.

**Comment by jjagielka** [comment]
There's a difference between an application and the framework.

The programmer is free to abuse any standards if that fits his needs in the application, however the framework should promote standards compliance and good practice.

**Comment by 524c** [comment]
If that bothers you too much, I can open a PR with a revert. I'm just a Flowbite user, which I like a lot because it's a very clean code. You along with @shinokada have been contributing to the project for a long time, it's ok 😁

> There's a difference between an application and the framework.
> 
> The programmer is free to abuse any standards if that fits his needs in the application, however the framework should promote standards compliance and good practice.

If that bothers you too much, I can open a PR with a revert. I'm just a Flowbite user, which I like a lot because it's a very clean code. You along with @shinokada have been contributing to the project for a long time, it's ok 😁

**Pull request merged**
